# Generated by Django 5.2.1 on 2025-05-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_requests", models.PositiveIntegerField()),
                ("unique_ips", models.PositiveIntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "API Analytics",
                "verbose_name_plural": "API Analytics",
            },
        ),
        migrations.CreateModel(
            name="APIRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("path", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DailyTraffic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("count", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Daily Traffic",
                "verbose_name_plural": "Daily Traffic",
            },
        ),
        migrations.CreateModel(
            name="EndpointStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=255)),
                ("count", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Endpoint Stat",
                "verbose_name_plural": "Endpoint Stats",
            },
        ),
    ]
