# Generated by Django 5.2.1 on 2025-05-09 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="apirequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dailytraffic",
            name="analytics",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_traffic",
                to="api.apianalytics",
            ),
        ),
        migrations.AddField(
            model_name="endpointstats",
            name="analytics",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="endpoints",
                to="api.apianalytics",
            ),
        ),
        migrations.AddIndex(
            model_name="apirequest",
            index=models.Index(
                fields=["ip_address"], name="api_apirequ_ip_addr_95253b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apirequest",
            index=models.Index(
                fields=["timestamp"], name="api_apirequ_timesta_69a2cc_idx"
            ),
        ),
    ]
