# Generated by Django 5.2.6 on 2025-10-01 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apirequest",
            name="query_params",
            field=models.JSONField(
                blank=True, help_text="GET/POST parameters for analysis", null=True
            ),
        ),
        migrations.CreateModel(
            name="EndpointAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("endpoint", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                (
                    "query_params",
                    models.JSONField(
                        blank=True, help_text="GET/POST parameters", null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Endpoint Access Log",
                "verbose_name_plural": "Endpoint Access Logs",
                "indexes": [
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="api_endpoin_ip_addr_098bb9_idx",
                    ),
                    models.Index(
                        fields=["endpoint", "timestamp"],
                        name="api_endpoin_endpoin_deb55a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="IPJourney",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                (
                    "endpoints_visited",
                    models.JSONField(help_text="List of endpoints visited by this IP"),
                ),
                (
                    "journey_length",
                    models.PositiveIntegerField(
                        help_text="Number of unique endpoints visited"
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "analytics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ip_journeys",
                        to="api.apianalytics",
                    ),
                ),
            ],
            options={
                "verbose_name": "IP Journey",
                "verbose_name_plural": "IP Journeys",
                "indexes": [
                    models.Index(
                        fields=["ip_address"], name="api_ipjourn_ip_addr_8cd405_idx"
                    ),
                    models.Index(
                        fields=["last_seen"], name="api_ipjourn_last_se_179013_idx"
                    ),
                ],
            },
        ),
    ]
