# Generated by Django 5.2.15 on 2026-07-07 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_apirequest_query_params_endpointaccesslog_ipjourney"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FlaggedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("velocity", "High request velocity"),
                            ("scan", "Endpoint scanning"),
                            ("strikes", "Security pattern strikes (SQLi/XSS/etc)"),
                            ("errors", "High 4xx/5xx error rate"),
                            ("manual", "Manually flagged"),
                            ("recurring", "Recurring offender (repeat ban)"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("flagged_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "ban_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the Redis ban expires. Null = permanent ban.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="If False, the IP is no longer banned (kept for history).",
                    ),
                ),
                (
                    "strike_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of security events that contributed to this flag.",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Admin notes about this IP (e.g. ' scraper from AWS, banned 2026-07-07')",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flagged IP",
                "verbose_name_plural": "Flagged IPs",
            },
        ),
        migrations.AddField(
            model_name="endpointaccesslog",
            name="flag_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Why this request was captured (e.g. velocity, strike, scan)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="endpointaccesslog",
            name="is_flagged",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True if this request was captured because the IP was flagged",
            ),
        ),
        migrations.AddField(
            model_name="endpointaccesslog",
            name="response_time_ms",
            field=models.PositiveIntegerField(
                blank=True, help_text="Response time in milliseconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="endpointaccesslog",
            name="status_code",
            field=models.PositiveIntegerField(
                blank=True, help_text="HTTP response status code", null=True
            ),
        ),
        migrations.AddField(
            model_name="endpointaccesslog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Authenticated user (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="endpointaccesslog",
            index=models.Index(
                fields=["is_flagged", "timestamp"],
                name="api_endpoin_is_flag_6c0b6c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="endpointaccesslog",
            index=models.Index(
                fields=["status_code", "timestamp"],
                name="api_endpoin_status__31f677_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="flaggedip",
            index=models.Index(
                fields=["is_active", "last_seen"], name="api_flagged_is_acti_be46e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flaggedip",
            index=models.Index(fields=["reason"], name="api_flagged_reason_d968fd_idx"),
        ),
    ]
