# Generated by Django 5.2.11 on 2026-03-06 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0042_fix_extra_field_type_nullable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person_name",
                    models.CharField(
                        blank=True,
                        help_text="Watch companies where this person is associated (director, representative, etc.)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "signer_name",
                    models.CharField(
                        blank=True,
                        help_text="Watch decisions signed by this person",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        blank=True,
                        help_text="List of keywords to match in decision subject/content",
                        null=True,
                    ),
                ),
                (
                    "amount_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum amount filter",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "amount_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum amount filter",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "decision_types",
                    models.JSONField(
                        blank=True,
                        help_text="List of decision type codes to filter by",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "last_checked",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this subscription was last checked for new decisions",
                        null=True,
                        verbose_name="Last checked",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="core.afmentity",
                        verbose_name="AFM Entity",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="core.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "relationship_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationship_subscriptions",
                        to="core.afmentity",
                        verbose_name="Relationship Entity",
                    ),
                ),
                (
                    "relationship_org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationship_subscriptions",
                        to="core.organization",
                        verbose_name="Relationship Organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Subscription",
                "verbose_name_plural": "Notification Subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_reason",
                    models.CharField(
                        choices=[
                            ("organization", "Organization match"),
                            ("entity", "Entity match"),
                            ("relationship", "Relationship match"),
                            ("person", "Person match"),
                            ("signer", "Signer match"),
                            ("filter", "Filter match"),
                            ("keyword_match", "Keyword match"),
                            ("amount_match", "Amount match"),
                        ],
                        help_text="What type of match triggered this notification",
                        max_length=50,
                        verbose_name="Match reason",
                    ),
                ),
                (
                    "match_details",
                    models.JSONField(
                        help_text="Details about what matched (keywords found, amounts, etc.)",
                        verbose_name="Match details",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has read this notification",
                        verbose_name="Read",
                    ),
                ),
                (
                    "is_dismissed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has dismissed this notification",
                        verbose_name="Dismissed",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification was marked as read",
                        null=True,
                        verbose_name="Read at",
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.decision",
                        verbose_name="Decision",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="notifications.notificationsubscription",
                        verbose_name="Subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notificationsubscription",
            index=models.Index(
                fields=["user", "is_active"], name="notificatio_user_id_485618_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationsubscription",
            index=models.Index(
                fields=["last_checked"], name="notificatio_last_ch_118ab5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationsubscription",
            index=models.Index(
                fields=["person_name"], name="notificatio_person__998113_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationsubscription",
            index=models.Index(
                fields=["signer_name"], name="notificatio_signer__dcd1dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="notificatio_user_id_427e4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "created_at"], name="notificatio_user_id_c62b26_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("user", "subscription", "decision"),
                name="unique_notification_per_user_subscription_decision",
            ),
        ),
    ]
