# Generated by Django 5.2.11 on 2026-03-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsubscription",
            name="check_frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("manual", "Manual only"),
                ],
                default="daily",
                help_text="How often to automatically check for new matching decisions",
                max_length=20,
                verbose_name="Check frequency",
            ),
        ),
    ]
