# Generated by Django 5.2.12 on 2026-03-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationsubscription_check_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsubscription",
            name="alias",
            field=models.CharField(
                blank=True,
                help_text="Optional custom name for this subscription",
                max_length=200,
                null=True,
                verbose_name="Alias",
            ),
        ),
    ]
