# Generated by Django 5.2.12 on 2026-03-08 11:05

from django.db import migrations


def remove_duplicate_subscriptions(apps, schema_editor):
    """
    Remove duplicate subscriptions, keeping only the oldest one for each unique combination.
    """
    NotificationSubscription = apps.get_model('notifications', 'NotificationSubscription')
    db_alias = schema_editor.connection.alias
    
    deleted_count = 0
    
    # Find and remove duplicate organization subscriptions
    org_subscriptions = NotificationSubscription.objects.using(db_alias).filter(
        organization__isnull=False
    ).values('user_id', 'organization_id').distinct()
    
    for combo in org_subscriptions:
        duplicates = NotificationSubscription.objects.using(db_alias).filter(
            user_id=combo['user_id'],
            organization_id=combo['organization_id']
        ).order_by('created_at')
        
        # Keep the first (oldest), delete the rest
        if duplicates.count() > 1:
            to_delete = list(duplicates.values_list('id', flat=True)[1:])
            deleted, _ = NotificationSubscription.objects.using(db_alias).filter(id__in=to_delete).delete()
            deleted_count += deleted
            print(f"Removed {deleted} duplicate organization subscriptions for user {combo['user_id']}, org {combo['organization_id']}")
    
    # Find and remove duplicate entity subscriptions
    entity_subscriptions = NotificationSubscription.objects.using(db_alias).filter(
        entity__isnull=False
    ).values('user_id', 'entity_id').distinct()
    
    for combo in entity_subscriptions:
        duplicates = NotificationSubscription.objects.using(db_alias).filter(
            user_id=combo['user_id'],
            entity_id=combo['entity_id']
        ).order_by('created_at')
        
        if duplicates.count() > 1:
            to_delete = list(duplicates.values_list('id', flat=True)[1:])
            deleted, _ = NotificationSubscription.objects.using(db_alias).filter(id__in=to_delete).delete()
            deleted_count += deleted
            print(f"Removed {deleted} duplicate entity subscriptions for user {combo['user_id']}, entity {combo['entity_id']}")
    
    # Find and remove duplicate relationship subscriptions
    relationship_subscriptions = NotificationSubscription.objects.using(db_alias).filter(
        relationship_org__isnull=False,
        relationship_entity__isnull=False
    ).values('user_id', 'relationship_org_id', 'relationship_entity_id').distinct()
    
    for combo in relationship_subscriptions:
        duplicates = NotificationSubscription.objects.using(db_alias).filter(
            user_id=combo['user_id'],
            relationship_org_id=combo['relationship_org_id'],
            relationship_entity_id=combo['relationship_entity_id']
        ).order_by('created_at')
        
        if duplicates.count() > 1:
            to_delete = list(duplicates.values_list('id', flat=True)[1:])
            deleted, _ = NotificationSubscription.objects.using(db_alias).filter(id__in=to_delete).delete()
            deleted_count += deleted
            print(f"Removed {deleted} duplicate relationship subscriptions for user {combo['user_id']}, org {combo['relationship_org_id']}, entity {combo['relationship_entity_id']}")
    
    # Find and remove duplicate person subscriptions
    person_subscriptions = NotificationSubscription.objects.using(db_alias).filter(
        person_name__isnull=False
    ).values('user_id', 'person_name').distinct()
    
    for combo in person_subscriptions:
        duplicates = NotificationSubscription.objects.using(db_alias).filter(
            user_id=combo['user_id'],
            person_name=combo['person_name']
        ).order_by('created_at')
        
        if duplicates.count() > 1:
            to_delete = list(duplicates.values_list('id', flat=True)[1:])
            deleted, _ = NotificationSubscription.objects.using(db_alias).filter(id__in=to_delete).delete()
            deleted_count += deleted
            print(f"Removed {deleted} duplicate person subscriptions for user {combo['user_id']}, person {combo['person_name']}")
    
    # Find and remove duplicate signer subscriptions
    signer_subscriptions = NotificationSubscription.objects.using(db_alias).filter(
        signer_name__isnull=False
    ).values('user_id', 'signer_name').distinct()
    
    for combo in signer_subscriptions:
        duplicates = NotificationSubscription.objects.using(db_alias).filter(
            user_id=combo['user_id'],
            signer_name=combo['signer_name']
        ).order_by('created_at')
        
        if duplicates.count() > 1:
            to_delete = list(duplicates.values_list('id', flat=True)[1:])
            deleted, _ = NotificationSubscription.objects.using(db_alias).filter(id__in=to_delete).delete()
            deleted_count += deleted
            print(f"Removed {deleted} duplicate signer subscriptions for user {combo['user_id']}, signer {combo['signer_name']}")
    
    print(f"Total duplicate subscriptions removed: {deleted_count}")


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationsubscription_alias'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_subscriptions, migrations.RunPython.noop),
    ]
