# Generated by Django 5.2.12 on 2026-03-08 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_fix_extra_field_type_nullable"),
        ("notifications", "0004_remove_duplicate_subscriptions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="notificationsubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organization__isnull", False)),
                fields=("user", "organization"),
                name="unique_user_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationsubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("entity__isnull", False)),
                fields=("user", "entity"),
                name="unique_user_entity",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationsubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("relationship_entity__isnull", False),
                    ("relationship_org__isnull", False),
                ),
                fields=("user", "relationship_org", "relationship_entity"),
                name="unique_user_relationship",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationsubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("person_name__isnull", False)),
                fields=("user", "person_name"),
                name="unique_user_person",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationsubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("signer_name__isnull", False)),
                fields=("user", "signer_name"),
                name="unique_user_signer",
            ),
        ),
    ]
