# Generated by Django 5.2.12 on 2026-03-11 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_fix_extra_field_type_nullable"),
        ("notifications", "0005_add_unique_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsubscription",
            name="keyword_match_operator",
            field=models.CharField(
                choices=[("AND", "All keywords (AND)"), ("OR", "Any keyword (OR)")],
                default="AND",
                help_text="How to combine multiple keywords",
                max_length=3,
                verbose_name="Keyword match operator",
            ),
        ),
        migrations.CreateModel(
            name="NotificationBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_window_start",
                    models.DateTimeField(
                        help_text="Start of the time range checked for matching decisions",
                        verbose_name="Check window start",
                    ),
                ),
                (
                    "check_window_end",
                    models.DateTimeField(
                        help_text="End of the time range checked for matching decisions",
                        verbose_name="Check window end",
                    ),
                ),
                (
                    "match_count",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of decisions that matched",
                        verbose_name="Match count",
                    ),
                ),
                (
                    "aggregate_stats",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Pre-computed stats: total_amount, avg_amount, decision_type_breakdown, etc.",
                        verbose_name="Aggregate statistics",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has viewed this batch",
                        verbose_name="Read",
                    ),
                ),
                (
                    "is_dismissed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has dismissed this batch",
                        verbose_name="Dismissed",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Read at"),
                ),
                (
                    "dismissed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dismissed at"
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        help_text="The subscription that triggered this batch",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="notifications.notificationsubscription",
                        verbose_name="Subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Batch",
                "verbose_name_plural": "Notification Batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationBatchDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_reason",
                    models.CharField(
                        help_text="Why this decision matched (e.g., 'keyword_match', 'amount_filter', 'organization')",
                        max_length=100,
                        verbose_name="Match reason",
                    ),
                ),
                (
                    "match_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Details about the match (e.g., which keywords matched, decision snapshot)",
                        verbose_name="Match details",
                    ),
                ),
                (
                    "is_viewed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has viewed this specific decision",
                        verbose_name="Viewed",
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Viewed at"
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Added at"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_decisions",
                        to="notifications.notificationbatch",
                        verbose_name="Batch",
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_batches",
                        to="core.decision",
                        verbose_name="Decision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Batch Decision",
                "verbose_name_plural": "Notification Batch Decisions",
                "ordering": ["-added_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notificationbatch",
            index=models.Index(
                fields=["user", "is_read", "is_dismissed"],
                name="notificatio_user_id_a2b395_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationbatch",
            index=models.Index(
                fields=["subscription", "created_at"],
                name="notificatio_subscri_2058a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationbatch",
            index=models.Index(
                fields=["created_at"], name="notificatio_created_0fbe0a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationbatch",
            constraint=models.UniqueConstraint(
                fields=("subscription", "check_window_start", "check_window_end"),
                name="unique_subscription_time_window",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationbatchdecision",
            index=models.Index(
                fields=["batch", "decision"], name="notificatio_batch_i_b79eb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationbatchdecision",
            index=models.Index(
                fields=["decision"], name="notificatio_decisio_f69a1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationbatchdecision",
            index=models.Index(
                fields=["is_viewed"], name="notificatio_is_view_7fb144_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationbatchdecision",
            constraint=models.UniqueConstraint(
                fields=("batch", "decision"), name="unique_batch_decision"
            ),
        ),
    ]
