# Generated by Django 5.2.12 on 2026-03-12 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_fix_extra_field_type_nullable"),
        (
            "notifications",
            "0006_notificationsubscription_keyword_match_operator_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationbatchdecision",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="Denormalized subscription reference to enable unique constraint across batches",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch_decisions",
                to="notifications.notificationsubscription",
                verbose_name="Subscription",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationbatchdecision",
            index=models.Index(
                fields=["subscription", "decision"],
                name="notificatio_subscri_27a04a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationbatchdecision",
            constraint=models.UniqueConstraint(
                fields=("subscription", "decision"), name="unique_subscription_decision"
            ),
        ),
    ]
