# Generated by Django 5.2.12 on 2026-03-12 18:47

from django.db import migrations


def populate_subscription_field(apps, schema_editor):
    """Populate subscription field from batch.subscription relationship."""
    NotificationBatchDecision = apps.get_model('notifications', 'NotificationBatchDecision')
    
    # Update all batch decisions to have the subscription from their batch
    batch_decisions = NotificationBatchDecision.objects.select_related('batch').all()
    
    for batch_decision in batch_decisions:
        batch_decision.subscription = batch_decision.batch.subscription
    
    # Bulk update
    if batch_decisions:
        NotificationBatchDecision.objects.bulk_update(batch_decisions, ['subscription'], batch_size=1000)


def reverse_populate(apps, schema_editor):
    """Reverse migration - set subscription to None."""
    NotificationBatchDecision = apps.get_model('notifications', 'NotificationBatchDecision')
    NotificationBatchDecision.objects.all().update(subscription=None)


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_add_subscription_to_batch_decision"),
    ]

    operations = [
        migrations.RunPython(populate_subscription_field, reverse_populate),
    ]
