# Generated by Django 5.2.12 on 2026-03-12 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0008_populate_subscription_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationbatchdecision",
            name="subscription",
            field=models.ForeignKey(
                default=1,
                help_text="Denormalized subscription reference to enable unique constraint across batches",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch_decisions",
                to="notifications.notificationsubscription",
                verbose_name="Subscription",
            ),
            preserve_default=False,
        ),
    ]
