# Generated by Django 5.2.12 on 2026-03-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0009_make_subscription_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationbatch",
            name="email_sent",
            field=models.BooleanField(
                default=False,
                help_text="Whether an email notification has been sent for this batch",
                verbose_name="Email sent",
            ),
        ),
        migrations.AddField(
            model_name="notificationbatch",
            name="email_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the email notification was sent",
                null=True,
                verbose_name="Email sent at",
            ),
        ),
        migrations.AddField(
            model_name="notificationsubscription",
            name="also_send_email",
            field=models.BooleanField(
                default=True, verbose_name="Also send email notifications"
            ),
        ),
    ]
