# Generated by Django 5.2.16 on 2026-07-28 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_pipelinedefinition_alter_documentanalysis_provider_and_more"),
        ("notifications", "0010_notificationbatch_email_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationbatch",
            name="ai_summary",
            field=models.TextField(
                blank=True,
                help_text="AI-generated summary of the decisions in this batch",
                null=True,
                verbose_name="AI summary",
            ),
        ),
        migrations.AddField(
            model_name="notificationbatch",
            name="ai_summary_completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="AI summary completed at"
            ),
        ),
        migrations.AddField(
            model_name="notificationbatch",
            name="ai_summary_error",
            field=models.TextField(
                blank=True, null=True, verbose_name="AI summary error"
            ),
        ),
        migrations.AddField(
            model_name="notificationbatch",
            name="ai_summary_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_batches",
                to="core.pipelinerun",
                verbose_name="AI summary pipeline run",
            ),
        ),
        migrations.AddField(
            model_name="notificationbatch",
            name="ai_summary_status",
            field=models.CharField(
                default="PENDING",
                help_text="PENDING / RUNNING / COMPLETED / FAILED / SKIPPED",
                max_length=20,
                verbose_name="AI summary status",
            ),
        ),
        migrations.AddField(
            model_name="notificationsubscription",
            name="ai_summary_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Generate an AI summary for each notification batch",
                verbose_name="Enable AI summary",
            ),
        ),
        migrations.AddField(
            model_name="notificationsubscription",
            name="ai_summary_pipeline",
            field=models.ForeignKey(
                blank=True,
                help_text="Which pipeline to use for summarization. Null = default.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="core.pipelinedefinition",
                verbose_name="AI summary pipeline",
            ),
        ),
    ]
