[pytest]
DJANGO_SETTINGS_MODULE = diavgeia_project.autodetect_test_settings
python_files = test_*.py
testpaths = core/tests
addopts = -ra -q --strict-markers
norecursedirs = pothen .git __pycache__ .pytest_cache node_modules
markers =
    fast: unit test that are fast and computationally cheap to run
    slow: unit tests that are slow but not computationally expensive to run
    super_slow: unit tests that are slow and computationally expensive to run
    requires_postgresql: tests that require a PostgreSQL database
    impossible: unit tests that are impossible to run because they contain heavy_fixtures not synced with the git
    integration: tests that ensure the integration of multiple components of the system