"""
Django settings for diavgeia_project project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
default_unsafe_secret_key = "django-insecure-_qy*f$4zd#u_)lt_v%2t*29g9f$rr0=u!-g=t#+6g+z0)u6zsi"
SECRET_KEY = os.getenv("SECRET_KEY", default_unsafe_secret_key) 



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG_ENV = os.getenv("DEBUG", "False")  # Get it as a string
DEBUG = DEBUG_ENV.lower() in ("true", "1", "t")  # Convert to boolean


FRONTEND_DOMAINS:list[str] = os.getenv("FRONTEND_DOMAINS", "http://localhost:3000").split(",")
FRONTEND_DOMAINS_clean:list[str] = [d.strip() for d in FRONTEND_DOMAINS]

if not FRONTEND_DOMAINS_clean and not DEBUG:
    raise ValueError("FRONTEND_DOMAINS must be set in production")
FRONTEND_HOSTNAMES = [
    urlparse(d).netloc for d in FRONTEND_DOMAINS_clean if urlparse(d).netloc
]

# Start with frontend hostnames
ALLOWED_HOSTS = FRONTEND_HOSTNAMES.copy()

# Add any additional hosts from environment
ALLOWED_HOSTS_ENV = os.getenv("ALLOWED_HOSTS")
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS.extend([host.strip() for host in ALLOWED_HOSTS_ENV.split(",")])

# If DEBUG is True, you might want to add common local hosts for convenience
if DEBUG:
    ALLOWED_HOSTS.extend(["localhost", "127.0.0.1"])

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core.apps.CoreConfig",
    "rest_framework",
    "rest_framework.authtoken",
    "admin_custom",
    "users",
    "api",
    "drf_yasg",
    "corsheaders"
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.BasicAuthentication",  # Add this for development
        "rest_framework.authentication.TokenAuthentication",
        # Add Clerk authentication class (we'll create this)
        "api.authentication.ClerkAuthentication",
        "api.authentication.ApiKeyAuthentication"
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    'DEFAULT_PARSER_CLASSES': [
        'api.parsers.SanitizedJSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "api.middleware.rate_limit.RateLimitMiddleware",
    "api.middleware.security.SecurityMonitoringMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "csp.middleware.CSPMiddleware"
]

ROOT_URLCONF = "diavgeia_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "diavgeia_project.wsgi.application"


# Cache configuration
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{os.environ.get('REDIS_HOST', 'redis')}:{os.environ.get('REDIS_PORT', '6379')}/{os.environ.get('REDIS_DB', '1')}",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": os.environ.get(
                "REDIS_PASSWORD", ""
            ),  # Empty string if no password
        },
    }
}

# Database configuration - use DATABASE_URL if available, otherwise individual vars
DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    # Parse DATABASE_URL
    from urllib.parse import urlparse
    parsed = urlparse(DATABASE_URL)
    
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": parsed.path.lstrip('/'),
            "USER": parsed.username,
            "PASSWORD": parsed.password,
            "HOST": parsed.hostname,
            "PORT": parsed.port or 5432,
            "OPTIONS": {
                "connect_timeout": 60,
                "options": "-c statement_timeout=300000"  # 5 minutes
            },
            "CONN_MAX_AGE": 0,  # Don't persist connections for remote DB
            "CONN_HEALTH_CHECKS": True,  # Enable connection health checks
        }
    }
else:
    # Fallback to individual environment variables
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB", "local_diavgia"),
            "USER": os.environ.get("POSTGRES_USER", "local_user"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "local_pass"),
            "HOST": os.environ.get("DB_HOST", "db"),
            "PORT": os.environ.get("DB_PORT", "5432"),
            "OPTIONS": {
                "connect_timeout": 60,
                "options": "-c statement_timeout=300000"  # 5 minutes
            },
            "CONN_MAX_AGE": 0,  # Don't persist connections for remote DB
            "CONN_HEALTH_CHECKS": True,  # Enable connection health checks
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/


TIME_ZONE = "Europe/Athens"
LANGUAGE_CODE = "en-us"

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = "users.CustomUser"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Celery settings
CELERY_BROKER_URL = os.environ.get(
    "CELERY_BROKER_URL", "amqp://guest:guest@localhost:5672//"
)
CELERY_RESULT_BACKEND = "django-db"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
CELERY_TASK_TRACK_STARTED = True
CELERY_RESULT_EXPIRES = 86400  # 1 day in seconds

# Worker Resource Limits
CELERY_WORKER_MAX_TASKS_PER_CHILD = int(os.environ.get("CELERY_WORKER_MAX_TASKS_PER_CHILD", 100))  # Restart worker process after 100 tasks to release memory
# Increased from 5 to amortize the heavy Docling initialization cost (5.4s per worker)
# This means the 5.4s overhead is spread across 100 documents instead of 5
CELERY_WORKER_MAX_MEMORY_PER_CHILD = int(os.environ.get("CELERY_WORKER_MAX_MEMORY_PER_CHILD", 2500000))  # 2.5GB (in KB) - Restart if memory exceeds this
# Increased from 1GB to accommodate Docling's memory requirements (~1.5-2GB peak with concurrency=2)

# Django Celery Results
INSTALLED_APPS += [
    "django_celery_results",
    "django_celery_beat",
]

CLERK_SECRET_KEY = os.getenv("CLERK_SECRET_KEY")
CLERK_JWT_PUBLIC_KEY = os.getenv("CLERK_JWT_PUBLIC_KEY")

# Use the first frontend hostname, or localhost:3000 in debug
# Auto-derive from frontend domains
if FRONTEND_HOSTNAMES:
    default_clerk_audience = FRONTEND_HOSTNAMES[0]
else:
    default_clerk_audience = "localhost:3000" if DEBUG else "your-domain.com"

CLERK_JWT_AUDIENCE = os.getenv("CLERK_JWT_AUDIENCE", default_clerk_audience)

#####CORS Settings#####

CORS_ALLOW_CREDENTIALS = True
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True  # Only in development
else:
    CORS_ALLOWED_ORIGINS = FRONTEND_DOMAINS_clean

# CSRF
CSRF_TRUSTED_ORIGINS = FRONTEND_DOMAINS_clean

# Important: Allow CORS headers for rate limiting responses
CORS_EXPOSE_HEADERS = [
    'X-RateLimit-Limit',
    'X-RateLimit-Remaining', 
    'X-RateLimit-Reset',
]

#####CORS Settings#####

# Create a common base list for Clerk CSP settings
CLERK_CSP_SOURCES = [
    "'self'", 
    "https://api.clerk.com", 
    *FRONTEND_DOMAINS_clean
]

#####Content Security Policy#####
CSP_DEFAULT_SRC = ["'self'"]
CSP_SCRIPT_SRC = CLERK_CSP_SOURCES
CSP_STYLE_SRC = ["'self'", "'unsafe-inline'"]  # Often needed for styling
CSP_CONNECT_SRC = CLERK_CSP_SOURCES
CSP_IMG_SRC = ["'self'", "https://img.clerk.com"]  # For Clerk avatars/images
CSP_FRAME_SRC = ["'self'", "https://accounts.clerk.dev"]  # For embedded iframes
#####Content Security Policy#####


#####Cookies#####
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = not DEBUG
    SESSION_COOKIE_SECURE = not DEBUG
    CSRF_COOKIE_SECURE = not DEBUG
#####Cookies#####

# OpenSearch Configuration
OPENSEARCH_URL = os.getenv('OPENSEARCH_URL', 'http://opensearch:9200')
OPENSEARCH_ENABLED = os.getenv('OPENSEARCH_ENABLED', 'true').lower() == 'true'

# Search Configuration
SEARCH_BACKEND = os.getenv('SEARCH_BACKEND', 'opensearch')  # 'opensearch', 'postgresql', or 'hybrid'

GEMI_API_KEY = os.getenv('GEMI_API_KEY', None)
GEMI_TIMEOUT = 30
GEMI_MAX_RETRIES = 3

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': '%(asctime)s %(name)s %(levelname)s %(message)s %(pathname)s %(lineno)d %(funcName)s %(process)d %(thread)d',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'json' if not DEBUG else 'verbose',
        },
        'console_debug': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler', 
            'formatter': 'verbose',
            'filters': ['require_debug_true'],
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'maxBytes': 1024*1024*15,  # 15MB
            'backupCount': 10,
            'formatter': 'json',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'],
            'formatter': 'verbose'
        }
    },
    'root': {
        'level': 'INFO',
        'handlers': ['console'],
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'file', 'mail_admins'],
            'level': 'INFO',
            'propagate': False,
        },
        # Custom app loggers
        'api': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'core': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'users': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Celery logging
        'celery': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery.task': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        # Third party
        'requests': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'urllib3': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    }
}

# Create logs directory if it doesn't exist
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)
