# Generated by Django 5.2.1 on 2025-05-28 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_api_key_customuser_usage_this_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="preferred_layout",
            field=models.CharField(default="horizontal-right", max_length=30),
        ),
        migrations.AddField(
            model_name="customuser",
            name="preferred_palette",
            field=models.CharField(default="blue", max_length=20),
        ),
        migrations.AddField(
            model_name="customuser",
            name="preferred_theme",
            field=models.CharField(default="light", max_length=20),
        ),
        migrations.AddField(
            model_name="subscription",
            name="max_saved_items",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name="subscription",
            name="max_search_history",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField()),
                ("filters", models.JSONField(blank=True, null=True)),
                ("results_count", models.IntegerField(blank=True, null=True)),
                ("search_type", models.CharField(default="general", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("decision_ada", models.CharField(max_length=50)),
                ("decision_subject", models.TextField()),
                ("decision_data", models.JSONField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("is_favorite", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("user", "decision_ada")},
            },
        ),
        migrations.CreateModel(
            name="SavedEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("ministry", "Ministry"),
                            ("organization", "Organization"),
                            ("unit", "Unit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("entity_id", models.CharField(max_length=50)),
                ("entity_name", models.CharField(max_length=255)),
                ("entity_data", models.JSONField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_entities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("user", "entity_type", "entity_id")},
            },
        ),
        migrations.CreateModel(
            name="VisitedEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entity_type", models.CharField(max_length=20)),
                ("entity_id", models.CharField(max_length=50)),
                ("entity_name", models.CharField(max_length=255)),
                ("visit_count", models.PositiveIntegerField(default=1)),
                ("last_visited", models.DateTimeField(auto_now=True)),
                ("first_visited", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visited_entities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_visited"],
                "unique_together": {("user", "entity_type", "entity_id")},
            },
        ),
    ]
