# Generated by Django 5.2.1 on 2025-05-28 15:35

from django.db import migrations


def populate_decision_fk(apps, schema_editor):
    SavedDecision = apps.get_model('users', 'SavedDecision')
    Decision = apps.get_model('core', 'Decision')

    for saved_decision in SavedDecision.objects.all():
        try:
            decision = Decision.objects.get(ada=saved_decision.decision_ada)
            saved_decision.decision = decision
            saved_decision.save()
        except Decision.DoesNotExist:
            # If decision doesn't exist, you could either:
            # 1. Delete the saved decision
            saved_decision.delete()
            # 2. Or keep it and handle later
            pass


def reverse_populate_decision_fk(apps, schema_editor):
    # If rolling back, populate ada from FK
    SavedDecision = apps.get_model('users', 'SavedDecision')

    for saved_decision in SavedDecision.objects.filter(decision__isnull=False):
        saved_decision.decision_ada = saved_decision.decision.ada
        saved_decision.save()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_add_decision_fk'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_decision_fk, reverse_populate_decision_fk),
    ]
