# Generated by Django 5.2.1 on 2025-05-28 15:39

from django.db import migrations


def remove_null_decisions(apps, schema_editor):
    SavedDecision = apps.get_model("users", "SavedDecision")
    # Remove any SavedDecision records with NULL decision FK
    # (Should be none since you already deleted all records)
    SavedDecision.objects.filter(decision__isnull=True).delete()


def reverse_remove_null_decisions(apps, schema_editor):
    # Can't reverse deletion, so do nothing
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_populate_decision_fk"),
    ]

    operations = [
        migrations.RunPython(remove_null_decisions, reverse_remove_null_decisions),
    ]
