# Generated by Django 5.2.1 on 2025-05-28 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_handle_null_decisions"),
    ]

    operations = [
        # Remove old unique_together constraint first
        migrations.AlterUniqueTogether(
            name="saveddecision",
            unique_together=set(),
        ),
        # Remove old fields
        migrations.RemoveField(
            model_name="saveddecision",
            name="decision_ada",
        ),
        migrations.RemoveField(
            model_name="saveddecision",
            name="decision_subject",
        ),
        migrations.RemoveField(
            model_name="saveddecision",
            name="decision_data",
        ),
        # Make FK non-nullable
        migrations.AlterField(
            model_name="saveddecision",
            name="decision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_by_users",
                to="core.decision",
                to_field="ada",
            ),
        ),
        # Add new unique_together constraint
        migrations.AlterUniqueTogether(
            name="saveddecision",
            unique_together={("user", "decision")},
        ),
    ]
