# Generated by Django 5.2.9 on 2025-12-28 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_finalize_decision_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="User's email address", max_length=254, unique=True
                    ),
                ),
                (
                    "clerk_user_id",
                    models.CharField(
                        blank=True,
                        help_text="Clerk user ID (optional, auto-filled on first login)",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="User's full name", max_length=255
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to temporarily revoke access without deleting",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about this user"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who added this user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_allowed_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Allowed User",
                "verbose_name_plural": "Allowed Users",
                "ordering": ["email"],
                "indexes": [
                    models.Index(fields=["email"], name="users_allow_email_7a2993_idx"),
                    models.Index(
                        fields=["clerk_user_id"], name="users_allow_clerk_u_3d6f2e_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="users_allow_is_acti_703293_idx"
                    ),
                ],
            },
        ),
    ]
