# Generated by Django 5.2.9 on 2026-01-01 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alloweduser"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="visitedentity",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="visitedentity",
            name="user",
        ),
        migrations.CreateModel(
            name="BookmarkFolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "color",
                    models.CharField(
                        default="#3b82f6",
                        help_text="Hex color code for folder",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon name or emoji", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent folder for nested organization",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subfolders",
                        to="users.bookmarkfolder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmark_folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("user", "name", "parent")},
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="User-defined title for the bookmark", max_length=255
                    ),
                ),
                (
                    "url",
                    models.TextField(
                        help_text="Full URL path including query parameters"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "view_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of view (e.g., temporal, entity, search, decision)",
                        max_length=50,
                    ),
                ),
                (
                    "preview_data",
                    models.JSONField(
                        blank=True,
                        help_text="Cached preview data (e.g., filter summary, result counts)",
                        null=True,
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                ("visit_count", models.PositiveIntegerField(default=0)),
                ("last_visited", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bookmarks",
                        to="users.bookmarkfolder",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.DeleteModel(
            name="SavedEntity",
        ),
        migrations.DeleteModel(
            name="VisitedEntity",
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["user", "is_favorite"], name="users_bookm_user_id_51ea1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["user", "folder"], name="users_bookm_user_id_7cc561_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookmark",
            index=models.Index(
                fields=["user", "-last_visited"], name="users_bookm_user_id_4bc517_idx"
            ),
        ),
    ]
