# Generated by Django 5.2.12 on 2026-03-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_visitedentity_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="preferred_language",
            field=models.CharField(
                choices=[("en", "English"), ("el", "Greek")],
                default="en",
                max_length=10,
            ),
        ),
    ]
