# Generated by Django 5.2.12 on 2026-03-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_customuser_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verification_token",
            field=models.UUIDField(
                blank=True, help_text="Token for email verification", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_verification_token_expires",
            field=models.DateTimeField(
                blank=True, help_text="Expiry time for verification token", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(
                default=False, help_text="Whether email has been verified"
            ),
        ),
    ]
