# Generated by Django 5.2.12 on 2026-04-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_customuser_email_verification_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="password_reset_token",
            field=models.UUIDField(
                blank=True, help_text="Token for password reset", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="password_reset_token_expires",
            field=models.DateTimeField(
                blank=True, help_text="Expiry time for password reset token", null=True
            ),
        ),
    ]
