# Generated by Django 5.2.15 on 2026-06-17 18:19
# Manually edited: split public_slug addition into add → populate → unique to avoid
# "Callable default on unique field will not generate unique values upon migrating."

import users.models
from django.db import migrations, models


def populate_public_slugs(apps, schema_editor):
    """Assign a unique random slug to every existing row.

    Regenerates slugs for ALL rows (not just null ones) to handle the case
    where a previous failed migration left duplicate default values behind.
    """
    Bookmark = apps.get_model("users", "Bookmark")
    BookmarkFolder = apps.get_model("users", "BookmarkFolder")

    for model_cls in [Bookmark, BookmarkFolder]:
        for obj in model_cls.objects.all():
            obj.public_slug = users.models._generate_public_slug()
            obj.save(update_fields=["public_slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_add_password_reset_fields"),
    ]

    operations = [
        # ── Bookmark: non-unique fields ──
        migrations.AddField(
            model_name="bookmark",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, this bookmark is publicly accessible via a share link",
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="public_created_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this bookmark was first made public",
                null=True,
            ),
        ),
        # ── Bookmark: add public_slug WITHOUT unique first ──
        migrations.AddField(
            model_name="bookmark",
            name="public_slug",
            field=models.CharField(
                blank=True,
                default=users.models._generate_public_slug,
                help_text="Unique slug for the public share URL",
                max_length=32,
                null=True,
            ),
        ),
        # ── BookmarkFolder: non-unique fields ──
        migrations.AddField(
            model_name="bookmarkfolder",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, this folder and its bookmarks are publicly accessible via a share link",
            ),
        ),
        migrations.AddField(
            model_name="bookmarkfolder",
            name="public_created_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this folder was first made public",
                null=True,
            ),
        ),
        # ── BookmarkFolder: add public_slug WITHOUT unique first ──
        migrations.AddField(
            model_name="bookmarkfolder",
            name="public_slug",
            field=models.CharField(
                blank=True,
                default=users.models._generate_public_slug,
                help_text="Unique slug for the public share URL",
                max_length=32,
                null=True,
            ),
        ),

        # ── Populate unique slugs for all existing rows ──
        migrations.RunPython(populate_public_slugs, migrations.RunPython.noop),

        # ── Now add the unique constraint ──
        migrations.AlterField(
            model_name="bookmark",
            name="public_slug",
            field=models.CharField(
                blank=True,
                default=users.models._generate_public_slug,
                help_text="Unique slug for the public share URL",
                max_length=32,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="bookmarkfolder",
            name="public_slug",
            field=models.CharField(
                blank=True,
                default=users.models._generate_public_slug,
                help_text="Unique slug for the public share URL",
                max_length=32,
                null=True,
                unique=True,
            ),
        ),
    ]
