# Generated by Django 5.2.16 on 2026-07-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_bookmark_is_public_bookmark_public_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="ai_spent_month",
            field=models.IntegerField(
                blank=True, help_text="YYYYMM for monthly reset logic", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="ai_spent_this_month_usd",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
