# Generated by Django 5.2.16 on 2026-07-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_customuser_ai_spent_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="ai_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Master switch — when off, no AI calls are made for this user.",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="ai_system_key_accepted",
            field=models.BooleanField(
                default=False,
                help_text="User has acknowledged using the platform system key for AI.",
            ),
        ),
    ]
