# Generated by Django 5.2.17 on 2026-08-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_customuser_ai_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="daily_request_limit_override",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Admin override for daily API request limit (null = use subscription default).",
                null=True,
            ),
        ),
    ]
