# Generated by Django 5.2 on 2025-04-23 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dictionary",
            fields=[
                (
                    "uid",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Dictionaries",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "uid",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("latin_name", models.CharField(max_length=255)),
                (
                    "abbreviation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                ("vat_number", models.CharField(blank=True, max_length=50, null=True)),
                ("fek_number", models.CharField(blank=True, max_length=50, null=True)),
                ("fek_issue", models.CharField(blank=True, max_length=50, null=True)),
                ("fek_year", models.CharField(blank=True, max_length=4, null=True)),
                ("website", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "supervisor_org_uid",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "supervisor_org_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DictionaryItem",
            fields=[
                (
                    "uid",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "dictionary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.dictionary",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="core.dictionaryitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="core.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "uid",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="core.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Signer",
            fields=[
                (
                    "uid",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("active_from", models.DateTimeField(blank=True, null=True)),
                ("active_until", models.DateTimeField(blank=True, null=True)),
                ("has_organization_sign_rights", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signers",
                        to="core.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "uid",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("active_from", models.DateTimeField(blank=True, null=True)),
                ("active_until", models.DateTimeField(blank=True, null=True)),
                ("category", models.CharField(max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="core.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="core.unit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnitDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255)),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="core.unit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SignerUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.position"
                    ),
                ),
                (
                    "signer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="core.signer",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.unit"
                    ),
                ),
            ],
            options={
                "unique_together": {("signer", "unit", "position")},
            },
        ),
    ]
