# Generated by Django 5.2 on 2025-04-28 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationGeoData",
            fields=[
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="geodata",
                        serialize=False,
                        to="core.organization",
                    ),
                ),
                ("place_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("place_rank", models.IntegerField(blank=True, null=True)),
                ("importance", models.FloatField(blank=True, null=True)),
                (
                    "addresstype",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("display_name", models.TextField(blank=True, null=True)),
                ("boundingbox", models.JSONField(blank=True, null=True)),
                ("geojson", models.JSONField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organization Geo Data",
                "verbose_name_plural": "Organization Geo Data",
            },
        ),
    ]
