# Generated by Django 5.2 on 2025-05-01 16:22

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_organizationgeodata"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActType",
            fields=[
                (
                    "uid",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=255)),
                ("allowed_in_decisions", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_types",
                        to="core.acttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Act Type",
                "verbose_name_plural": "Act Types",
            },
        ),
        migrations.CreateModel(
            name="ActTypeHelp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "act_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="help_text",
                        to="core.acttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Act Type Help",
                "verbose_name_plural": "Act Type Help",
            },
        ),
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ada",
                    models.CharField(
                        db_index=True,
                        help_text="The unique identifier (ΑΔΑ) of the decision.",
                        max_length=15,
                        unique=True,
                        verbose_name="ΑΔΑ",
                    ),
                ),
                ("version_id", models.CharField(max_length=36)),
                (
                    "corrected_version_id",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                (
                    "protocol_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("subject", models.TextField()),
                ("issue_date", models.DateTimeField()),
                (
                    "thematic_category_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of thematic category IDs (e.g., ['12.1', '12.2']). Consider FK/M2M if querying by category is needed.",
                        verbose_name="Thematic Category IDs",
                    ),
                ),
                (
                    "has_private_data",
                    models.BooleanField(
                        default=False, verbose_name="Contains Private Data"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PUBLISHED", "Published"),
                            ("REVOKED", "Revoked"),
                            ("PENDING_REVOCATION", "Pending Revocation"),
                            ("ALL", "All"),
                        ],
                        db_index=True,
                        max_length=25,
                        verbose_name="Status",
                    ),
                ),
                (
                    "document_url",
                    models.URLField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="Document URL",
                    ),
                ),
                (
                    "document_checksum",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Document Checksum",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="Diavgeia URL",
                    ),
                ),
                (
                    "warnings",
                    models.TextField(blank=True, null=True, verbose_name="Warnings"),
                ),
                (
                    "submission_timestamp",
                    models.DateTimeField(verbose_name="Submission Timestamp"),
                ),
                (
                    "publish_timestamp",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Publish Timestamp",
                    ),
                ),
                (
                    "financial_year",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Extracted from extraFieldValues.financialYear",
                        null=True,
                        verbose_name="Financial Year",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The primary financial amount (e.g., from amountWithVAT or awardAmount)",
                        max_digits=15,
                        null=True,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        help_text="Currency code for the primary amount",
                        max_length=3,
                        null=True,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "extra_field_values_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores the original extraFieldValues JSON data.",
                        null=True,
                        verbose_name="Raw Extra Field Values",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "decision_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="core.acttype",
                        verbose_name="Decision Type",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="core.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "signers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="signed_decisions",
                        to="core.signer",
                        verbose_name="Signers",
                    ),
                ),
                (
                    "units",
                    models.ManyToManyField(
                        blank=True,
                        related_name="decisions",
                        to="core.unit",
                        verbose_name="Organizational Units",
                    ),
                ),
            ],
            options={
                "verbose_name": "Decision",
                "verbose_name_plural": "Decisions",
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment_id",
                    models.CharField(
                        help_text="The ID of the attachment as provided by Diavgeia.",
                        max_length=255,
                        verbose_name="Attachment ID (from source)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="Filename")),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="MIME Type"),
                ),
                ("checksum", models.CharField(max_length=64, verbose_name="Checksum")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.decision",
                        verbose_name="Decision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
            },
        ),
        migrations.CreateModel(
            name="DecisionAmountKAE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kae",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="KAE Code"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Amount (with VAT)",
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kae_amounts",
                        to="core.decision",
                        verbose_name="Decision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Decision KAE Amount",
                "verbose_name_plural": "Decision KAE Amounts",
            },
        ),
        migrations.CreateModel(
            name="ExtraField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=255)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("object", "Object"),
                            ("date", "Date"),
                            ("monetary", "Monetary"),
                        ],
                        max_length=50,
                    ),
                ),
                ("validation", models.CharField(blank=True, max_length=255, null=True)),
                ("required", models.BooleanField(default=False)),
                ("multiple", models.BooleanField(default=False)),
                ("max_length", models.IntegerField(default=0)),
                ("dictionary", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "search_term",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("rel_ada_decision_types", models.JSONField(blank=True, null=True)),
                (
                    "rel_ada_constrained_in_organization",
                    models.BooleanField(blank=True, null=True),
                ),
                ("fixed_value_list", models.JSONField(blank=True, null=True)),
                (
                    "act_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_fields",
                        to="core.acttype",
                    ),
                ),
                (
                    "parent_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nested_fields",
                        to="core.extrafield",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extra Field",
                "verbose_name_plural": "Extra Fields",
                "ordering": ["act_type", "uid"],
            },
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["issue_date"], name="core_decisi_issue_d_3d1e92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["publish_timestamp"], name="core_decisi_publish_5f4c75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["filename"], name="core_attach_filenam_9ff065_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["mime_type"], name="core_attach_mime_ty_628ca1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attachment",
            unique_together={("decision", "attachment_id")},
        ),
        migrations.AddIndex(
            model_name="decisionamountkae",
            index=models.Index(fields=["kae"], name="core_decisi_kae_00f017_idx"),
        ),
        migrations.AddIndex(
            model_name="decisionamountkae",
            index=models.Index(
                fields=["decision", "kae"], name="core_decisi_decisio_21023b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="decisionamountkae",
            unique_together={("decision", "kae")},
        ),
        migrations.AlterUniqueTogether(
            name="extrafield",
            unique_together={("uid", "act_type")},
        ),
    ]
