# Generated by Django 5.2 on 2025-05-07 11:59

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_acttype_acttypehelp_decision_attachment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_type", models.CharField(max_length=50)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("PLAINTEXT", "Plain Text"),
                            ("DOCLING", "Docling"),
                            ("PYPDF", "PyPDF"),
                            ("PDFMINER", "PDF Miner"),
                            ("TESSERACT", "Tesseract OCR"),
                            ("GOOGLE_VISION", "Google Vision API"),
                            ("AZURE_OCR", "Azure OCR"),
                            ("OPENAI", "OpenAI"),
                            ("ANTHROPIC", "Anthropic Claude"),
                            ("GOOGLE_VERTEX", "Google Vertex AI"),
                            ("MISTRAL", "Mistral AI"),
                            ("OLLAMA", "Ollama Local Models"),
                            ("OPENAI_EMBED", "OpenAI Embeddings"),
                            ("GOOGLE_EMBED", "Google Embeddings"),
                            ("SENTENCE_TRANSFORMERS", "Sentence Transformers"),
                        ],
                        max_length=30,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_results",
                        to="core.decision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Analysis",
                "verbose_name_plural": "Document Analyses",
                "indexes": [
                    models.Index(
                        fields=["analysis_type"], name="core_docume_analysi_de713a_idx"
                    ),
                    models.Index(
                        fields=["provider"], name="core_docume_provide_9742a0_idx"
                    ),
                ],
                "unique_together": {
                    ("decision", "analysis_type", "provider", "version")
                },
            },
        ),
        migrations.CreateModel(
            name="DocumentEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.IntegerField()),
                ("chunk_text", models.TextField()),
                (
                    "embedding_provider",
                    models.CharField(
                        choices=[
                            ("PLAINTEXT", "Plain Text"),
                            ("DOCLING", "Docling"),
                            ("PYPDF", "PyPDF"),
                            ("PDFMINER", "PDF Miner"),
                            ("TESSERACT", "Tesseract OCR"),
                            ("GOOGLE_VISION", "Google Vision API"),
                            ("AZURE_OCR", "Azure OCR"),
                            ("OPENAI", "OpenAI"),
                            ("ANTHROPIC", "Anthropic Claude"),
                            ("GOOGLE_VERTEX", "Google Vertex AI"),
                            ("MISTRAL", "Mistral AI"),
                            ("OLLAMA", "Ollama Local Models"),
                            ("OPENAI_EMBED", "OpenAI Embeddings"),
                            ("GOOGLE_EMBED", "Google Embeddings"),
                            ("SENTENCE_TRANSFORMERS", "Sentence Transformers"),
                        ],
                        max_length=30,
                    ),
                ),
                ("embedding_model", models.CharField(max_length=100)),
                ("embedding_dimensions", models.IntegerField()),
                ("vector_json", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="core.decision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Embedding",
                "verbose_name_plural": "Document Embeddings",
                "indexes": [
                    models.Index(
                        fields=["embedding_provider"],
                        name="core_docume_embeddi_23ee48_idx",
                    ),
                    models.Index(
                        fields=["decision", "chunk_index"],
                        name="core_docume_decisio_31afb3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentExtraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extraction_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("NEEDS_VISION", "Needs Vision Processing"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "extraction_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PLAINTEXT", "Plain Text"),
                            ("DOCLING", "Docling"),
                            ("PYPDF", "PyPDF"),
                            ("PDFMINER", "PDF Miner"),
                            ("TESSERACT", "Tesseract OCR"),
                            ("GOOGLE_VISION", "Google Vision API"),
                            ("AZURE_OCR", "Azure OCR"),
                            ("OPENAI", "OpenAI"),
                            ("ANTHROPIC", "Anthropic Claude"),
                            ("GOOGLE_VERTEX", "Google Vertex AI"),
                            ("MISTRAL", "Mistral AI"),
                            ("OLLAMA", "Ollama Local Models"),
                            ("OPENAI_EMBED", "OpenAI Embeddings"),
                            ("GOOGLE_EMBED", "Google Embeddings"),
                            ("SENTENCE_TRANSFORMERS", "Sentence Transformers"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("extraction_date", models.DateTimeField(blank=True, null=True)),
                ("raw_text", models.TextField(blank=True, null=True)),
                ("page_count", models.IntegerField(blank=True, null=True)),
                ("character_count", models.IntegerField(blank=True, null=True)),
                ("is_scanned_document", models.BooleanField(blank=True, null=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("processing_time_ms", models.IntegerField(blank=True, null=True)),
                (
                    "task_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_extraction",
                        to="core.decision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Extraction",
                "verbose_name_plural": "Document Extractions",
                "indexes": [
                    models.Index(
                        fields=["extraction_status"],
                        name="core_docume_extract_5ec532_idx",
                    ),
                    models.Index(
                        fields=["extraction_provider"],
                        name="core_docume_extract_bd69fc_idx",
                    ),
                    models.Index(
                        fields=["is_scanned_document"],
                        name="core_docume_is_scan_1aa8dc_idx",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="core_docume_search__d7ddb0_gin"
                    ),
                ],
            },
        ),
    ]
