# Generated by Django 5.2.1 on 2025-05-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_update_search_vector_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentanalysis",
            name="provider",
            field=models.CharField(
                choices=[
                    ("PYMUPDF", "PyMuPDF"),
                    ("PLAINTEXT", "Plain Text"),
                    ("DOCLING", "Docling"),
                    ("PYPDF", "PyPDF"),
                    ("PDFMINER", "PDF Miner"),
                    ("TESSERACT", "Tesseract OCR"),
                    ("GOOGLE_VISION", "Google Vision API"),
                    ("AZURE_OCR", "Azure OCR"),
                    ("OPENAI", "OpenAI"),
                    ("ANTHROPIC", "Anthropic Claude"),
                    ("GOOGLE_VERTEX", "Google Vertex AI"),
                    ("MISTRAL", "Mistral AI"),
                    ("OLLAMA", "Ollama Local Models"),
                    ("OPENAI_EMBED", "OpenAI Embeddings"),
                    ("GOOGLE_EMBED", "Google Embeddings"),
                    ("SENTENCE_TRANSFORMERS", "Sentence Transformers"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="documentembedding",
            name="embedding_provider",
            field=models.CharField(
                choices=[
                    ("PYMUPDF", "PyMuPDF"),
                    ("PLAINTEXT", "Plain Text"),
                    ("DOCLING", "Docling"),
                    ("PYPDF", "PyPDF"),
                    ("PDFMINER", "PDF Miner"),
                    ("TESSERACT", "Tesseract OCR"),
                    ("GOOGLE_VISION", "Google Vision API"),
                    ("AZURE_OCR", "Azure OCR"),
                    ("OPENAI", "OpenAI"),
                    ("ANTHROPIC", "Anthropic Claude"),
                    ("GOOGLE_VERTEX", "Google Vertex AI"),
                    ("MISTRAL", "Mistral AI"),
                    ("OLLAMA", "Ollama Local Models"),
                    ("OPENAI_EMBED", "OpenAI Embeddings"),
                    ("GOOGLE_EMBED", "Google Embeddings"),
                    ("SENTENCE_TRANSFORMERS", "Sentence Transformers"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="documentextraction",
            name="extraction_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PYMUPDF", "PyMuPDF"),
                    ("PLAINTEXT", "Plain Text"),
                    ("DOCLING", "Docling"),
                    ("PYPDF", "PyPDF"),
                    ("PDFMINER", "PDF Miner"),
                    ("TESSERACT", "Tesseract OCR"),
                    ("GOOGLE_VISION", "Google Vision API"),
                    ("AZURE_OCR", "Azure OCR"),
                    ("OPENAI", "OpenAI"),
                    ("ANTHROPIC", "Anthropic Claude"),
                    ("GOOGLE_VERTEX", "Google Vertex AI"),
                    ("MISTRAL", "Mistral AI"),
                    ("OLLAMA", "Ollama Local Models"),
                    ("OPENAI_EMBED", "OpenAI Embeddings"),
                    ("GOOGLE_EMBED", "Google Embeddings"),
                    ("SENTENCE_TRANSFORMERS", "Sentence Transformers"),
                ],
                max_length=30,
                null=True,
            ),
        ),
    ]
