# Generated by Django 5.2.1 on 2025-05-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007c_add_pgvector_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="signer",
            name="resolution_path",
            field=models.JSONField(
                blank=True,
                help_text="Tracks how organization was resolved if not directly specified",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="resolution_path",
            field=models.JSONField(
                blank=True,
                help_text="Tracks how organization was resolved if not directly specified",
                null=True,
            ),
        ),
    ]
