# Generated by Django 5.2.1 on 2025-05-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_importjob_datecoverage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="organization",
        ),
    ]
