# Generated by Django 5.2.1 on 2025-05-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_organization_from_position"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="decisionamountkae",
            name="core_decisi_decisio_21023b_idx",
        ),
        migrations.AddField(
            model_name="decision",
            name="issue_date_day",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Date part only for efficient grouping",
                null=True,
                verbose_name="Issue Date (Day Only)",
            ),
        ),
        migrations.AddField(
            model_name="decision",
            name="issue_date_month",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="First day of month for grouping",
                null=True,
                verbose_name="Issue Date (Month Only)",
            ),
        ),
        migrations.AddField(
            model_name="decision",
            name="issue_date_year",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="Issue Year"
            ),
        ),
        migrations.RunSQL(
            """
            UPDATE core_decision
            SET
                issue_date_day = DATE(issue_date),
                issue_date_month = DATE_TRUNC('month', issue_date)::date,
                issue_date_year = EXTRACT(year FROM issue_date)
            WHERE issue_date IS NOT NULL;
            """,
            reverse_sql="""
            UPDATE core_decision
            SET issue_date_day=NULL, issue_date_month=NULL, issue_date_year=NULL;
            """,
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(fields=["ada"], name="core_decisi_ada_2fe636_idx"),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(fields=["status"], name="core_decisi_status_334a44_idx"),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["organization"], name="core_decisi_organiz_6822cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["organization", "issue_date"],
                name="core_decisi_organiz_be883b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["organization", "status"], name="core_decisi_organiz_1e6cba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["issue_date", "status"], name="core_decisi_issue_d_4bb799_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["amount", "issue_date"], name="core_decisi_amount_581d2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["financial_year", "organization"],
                name="core_decisi_financi_fc7582_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["organization", "issue_date_day"],
                name="core_decisi_organiz_7b4cb8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["organization", "issue_date_month"],
                name="core_decisi_organiz_42e7d6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["organization", "issue_date_year"],
                name="core_decisi_organiz_e31958_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["issue_date_month", "amount"],
                name="core_decisi_issue_d_93d05a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="decisionamountkae",
            index=models.Index(
                fields=["decision", "amount"], name="core_decisi_decisio_b18526_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="decisionamountkae",
            index=models.Index(fields=["amount"], name="core_decisi_amount_c98eaf_idx"),
        ),
    ]
