# Generated by Django 5.2.1 on 2025-05-26 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_add_decision_date_trigger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "normalized_query",
                    models.CharField(
                        db_index=True,
                        max_length=500,
                        unique=True,
                        verbose_name="Normalized Query",
                    ),
                ),
                (
                    "search_count",
                    models.IntegerField(default=0, verbose_name="Search Count"),
                ),
                (
                    "click_count",
                    models.IntegerField(default=0, verbose_name="Click Count"),
                ),
                (
                    "avg_results_count",
                    models.FloatField(default=0, verbose_name="Average Results Count"),
                ),
                (
                    "click_through_rate",
                    models.FloatField(default=0, verbose_name="Click Through Rate"),
                ),
                (
                    "entity_types",
                    models.JSONField(
                        default=dict,
                        help_text="Count by entity type",
                        verbose_name="Entity Types",
                    ),
                ),
                (
                    "search_types",
                    models.JSONField(
                        default=dict,
                        help_text="Count by search type",
                        verbose_name="Search Types",
                    ),
                ),
                (
                    "first_searched",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="First Searched"
                    ),
                ),
                (
                    "last_searched",
                    models.DateTimeField(auto_now=True, verbose_name="Last Searched"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
            ],
            options={
                "verbose_name": "Popular Query",
                "verbose_name_plural": "Popular Queries",
                "indexes": [
                    models.Index(
                        fields=["-search_count", "-click_through_rate"],
                        name="core_popula_search__9ec233_idx",
                    ),
                    models.Index(
                        fields=["-last_searched"], name="core_popula_last_se_e6b996_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        db_index=True, max_length=500, verbose_name="Search Query"
                    ),
                ),
                (
                    "normalized_query",
                    models.CharField(
                        db_index=True,
                        help_text="Lowercased, trimmed query for grouping",
                        max_length=500,
                        verbose_name="Normalized Query",
                    ),
                ),
                (
                    "search_types",
                    models.JSONField(
                        default=list,
                        help_text="Types searched: ['metadata', 'content', 'summary']",
                        verbose_name="Search Types",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="Entity Type",
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Entity ID",
                    ),
                ),
                (
                    "results_count",
                    models.IntegerField(default=0, verbose_name="Results Count"),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Response Time (ms)"
                    ),
                ),
                (
                    "user_clicked_result",
                    models.BooleanField(
                        default=False, verbose_name="User Clicked Result"
                    ),
                ),
                (
                    "clicked_result_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Clicked Result Type",
                    ),
                ),
                (
                    "clicked_result_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Clicked Result ID",
                    ),
                ),
                (
                    "click_position",
                    models.IntegerField(
                        blank=True,
                        help_text="Position of clicked result (1-based)",
                        null=True,
                        verbose_name="Click Position",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=40,
                        null=True,
                        verbose_name="Session Key",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "filters_applied",
                    models.JSONField(
                        default=dict,
                        help_text="Filters like date range, status, etc.",
                        verbose_name="Filters Applied",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Search Analytics",
                "verbose_name_plural": "Search Analytics",
                "indexes": [
                    models.Index(
                        fields=["normalized_query", "entity_type"],
                        name="core_search_normali_0374e9_idx",
                    ),
                    models.Index(
                        fields=["created_at", "results_count"],
                        name="core_search_created_828f61_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="core_search_user_id_636795_idx",
                    ),
                    models.Index(
                        fields=["session_key", "created_at"],
                        name="core_search_session_f5d98a_idx",
                    ),
                ],
            },
        ),
    ]
