# Generated by Django 5.2.1 on 2025-05-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_popularquery_searchanalytics"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("decisions", "Decisions"),
                            ("organizations", "Organizations"),
                            ("signers", "Signers"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("last_sync_timestamp", models.DateTimeField()),
                ("last_sync_date", models.DateField(blank=True, null=True)),
                ("total_processed", models.IntegerField(default=0)),
                ("last_run_status", models.CharField(default="pending", max_length=20)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "core_sync_status",
            },
        ),
    ]
