# Generated by Django 5.2.1 on 2025-05-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_syncstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decisionamountkae",
            name="kae",
            field=models.CharField(
                db_index=True, max_length=40, verbose_name="KAE Code"
            ),
        ),
    ]
