# Generated by Django 5.2.1 on 2025-06-01 10:10

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_decisionamountkae_kae"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.IntegerField()),
                ("raw_text", models.TextField(blank=True, null=True)),
                ("character_count", models.IntegerField(blank=True, null=True)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        blank=True, null=True
                    ),
                ),
                ("has_images", models.BooleanField(default=False)),
                ("has_tables", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "extraction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="core.documentextraction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Page",
                "verbose_name_plural": "Document Pages",
                "indexes": [
                    models.Index(
                        fields=["page_number"], name="core_docume_page_nu_1984b7_idx"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["search_vector"], name="core_docume_search__9e73d9_gin"
                    ),
                ],
                "unique_together": {("extraction", "page_number")},
            },
        ),
    ]
