# Generated by Django 5.2.1 on 2025-06-02 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_documentpage"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="datecoverage",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="datecoverage",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.unit",
            ),
        ),
        migrations.AddField(
            model_name="importjob",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.unit",
                verbose_name="Unit",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="datecoverage",
            unique_together={("date", "organization", "unit", "signer")},
        ),
    ]
