# Generated by Django 5.2.1 on 2025-06-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_datecoverage_unique_together_datecoverage_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentextraction",
            name="preprocessing_metadata",
            field=models.JSONField(
                blank=True,
                help_text="Metadata from text preprocessing including corruption detection",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="documentextraction",
            name="extraction_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("NEEDS_VISION", "Needs Vision Processing"),
                    ("CORRUPTED_CONTENT", "Corrupted Content Detected"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
