# Generated by Django 5.2.2 on 2025-06-09 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_documentextraction_preprocessing_metadata_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AFMEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("afm", models.CharField(db_index=True, max_length=20, unique=True)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("person", "Person"),
                            ("company", "Company"),
                            ("organization", "Organization"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("total_appearances", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "AFM Entity",
                "verbose_name_plural": "AFM Entities",
            },
        ),
        migrations.CreateModel(
            name="DecisionEntityRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("sponsorAFMName", "Sponsor"),
                            ("org", "Organization"),
                            ("person", "Person"),
                            ("grantor", "Grantor"),
                            ("grantee", "Grantee"),
                            ("donationGiver", "Donation Giver"),
                            ("donationReceiver", "Donation Receiver"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("parent_key_path", models.CharField(max_length=200)),
                (
                    "source_field_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("raw_context", models.JSONField(blank=True, null=True)),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                ("confidence_score", models.FloatField(default=1.0)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_relationships",
                        to="core.decision",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decision_relationships",
                        to="core.afmentity",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["decision", "role"],
                        name="core_decisi_decisio_be61cc_idx",
                    ),
                    models.Index(
                        fields=["entity", "role"], name="core_decisi_entity__250e6d_idx"
                    ),
                ],
                "unique_together": {("decision", "entity", "role", "parent_key_path")},
            },
        ),
    ]
