# Generated by Django 5.2.3 on 2025-07-10 08:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_afmentity_decisionentityrelationship"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ar_gemi",
                    models.BigIntegerField(
                        db_index=True, help_text="GEMI registration number", unique=True
                    ),
                ),
                (
                    "afm",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Tax identification number (AFM)",
                        max_length=9,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{9}$", "AFM must be exactly 9 digits"
                            )
                        ],
                    ),
                ),
                (
                    "co_name_el",
                    models.TextField(
                        blank=True, help_text="Company name in Greek", null=True
                    ),
                ),
                (
                    "co_names_en",
                    models.JSONField(
                        default=list, help_text="Company names in English"
                    ),
                ),
                (
                    "co_titles_el",
                    models.JSONField(default=list, help_text="Company titles in Greek"),
                ),
                (
                    "co_titles_en",
                    models.JSONField(
                        default=list, help_text="Company titles in English"
                    ),
                ),
                ("municipality_id", models.IntegerField(blank=True, null=True)),
                (
                    "municipality_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("prefecture_id", models.IntegerField(blank=True, null=True)),
                (
                    "prefecture_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "street_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
                ("po_box", models.CharField(blank=True, max_length=50, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("is_branch", models.BooleanField(blank=True, null=True)),
                (
                    "objective",
                    models.TextField(
                        blank=True, help_text="Company business objective", null=True
                    ),
                ),
                ("legal_type_id", models.IntegerField(blank=True, null=True)),
                (
                    "legal_type_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("gemi_office_id", models.IntegerField(blank=True, null=True)),
                (
                    "gemi_office_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "incorporation_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "last_status_change",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("status_id", models.IntegerField(blank=True, null=True)),
                (
                    "status_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("auto_registered", models.BooleanField(blank=True, null=True)),
                (
                    "branch_gemi_numbers",
                    models.JSONField(default=list, help_text="Branch GEMI numbers"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Last update from GEMI API",
                    ),
                ),
            ],
            options={
                "db_table": "companies",
                "indexes": [
                    models.Index(
                        fields=["ar_gemi"], name="companies_ar_gemi_f6e74f_idx"
                    ),
                    models.Index(fields=["afm"], name="companies_afm_a3eddc_idx"),
                    models.Index(
                        fields=["co_name_el"], name="companies_co_name_65848c_idx"
                    ),
                    models.Index(
                        fields=["municipality_id"], name="companies_municip_532037_idx"
                    ),
                    models.Index(
                        fields=["prefecture_id"], name="companies_prefect_21f4f2_idx"
                    ),
                    models.Index(
                        fields=["legal_type_id"], name="companies_legal_t_611a71_idx"
                    ),
                    models.Index(
                        fields=["status_id"], name="companies_status__2a06f9_idx"
                    ),
                    models.Index(
                        fields=["last_updated"], name="companies_last_up_6f32d0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanyCapital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capital_stock",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "ecsokefalaiikes",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "eggiitikes",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capital",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "company_capital",
            },
        ),
        migrations.CreateModel(
            name="CompanyActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_id",
                    models.CharField(help_text="Activity code/ID", max_length=50),
                ),
                ("activity_name", models.TextField(help_text="Activity description")),
                ("activity_type", models.CharField(max_length=100)),
                ("date_from", models.CharField(blank=True, max_length=50, null=True)),
                ("date_to", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "company_activities",
                "indexes": [
                    models.Index(
                        fields=["company", "activity_id"],
                        name="company_act_company_82ba3e_idx",
                    ),
                    models.Index(
                        fields=["activity_id"], name="company_act_activit_3f78f7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanyPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "business_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("role", models.CharField(blank=True, max_length=255, null=True)),
                ("date_from", models.CharField(blank=True, max_length=50, null=True)),
                ("date_to", models.CharField(blank=True, max_length=50, null=True)),
                ("is_representative_alone", models.BooleanField(blank=True, null=True)),
                (
                    "is_representative_in_common",
                    models.BooleanField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persons",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "company_persons",
                "indexes": [
                    models.Index(
                        fields=["company"], name="company_per_company_16f042_idx"
                    ),
                    models.Index(
                        fields=["person_name"], name="company_per_person__de03e9_idx"
                    ),
                    models.Index(fields=["role"], name="company_per_role_ec7ffd_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompanyStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_type_id", models.IntegerField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "nominal_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("stock_type", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "db_table": "company_stocks",
                "indexes": [
                    models.Index(
                        fields=["company"], name="company_sto_company_0629b4_idx"
                    ),
                    models.Index(
                        fields=["stock_type_id"], name="company_sto_stock_t_87233b_idx"
                    ),
                ],
            },
        ),
    ]
