# Generated by Django 5.2.3 on 2025-07-10 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_company_companycapital_companyactivity_companyperson_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="afmentity",
            name="error_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of failed lookup attempts"
            ),
        ),
        migrations.AddField(
            model_name="afmentity",
            name="gemi_companies_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of companies found with this AFM"
            ),
        ),
        migrations.AddField(
            model_name="afmentity",
            name="gemi_lookup_attempted",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the last GEMI lookup attempt",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="afmentity",
            name="gemi_lookup_success",
            field=models.BooleanField(
                default=False, help_text="Whether the last GEMI lookup was successful"
            ),
        ),
        migrations.AddField(
            model_name="afmentity",
            name="last_error",
            field=models.TextField(
                blank=True,
                help_text="Last error encountered during GEMI lookup",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="afmentity",
            name="afm",
            field=models.CharField(
                db_index=True,
                help_text="Tax identification number (AFM)",
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{9}$", "AFM must be exactly 9 digits"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="afmentity",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("person", "Person"),
                    ("company", "Company"),
                    ("organization", "Organization"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="Type of entity",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="afmentity",
            name="first_seen",
            field=models.DateTimeField(
                auto_now_add=True, help_text="First time this AFM was seen"
            ),
        ),
        migrations.AlterField(
            model_name="afmentity",
            name="last_seen",
            field=models.DateTimeField(
                auto_now=True, help_text="Last time this AFM was seen"
            ),
        ),
        migrations.AlterField(
            model_name="afmentity",
            name="name",
            field=models.TextField(
                blank=True, help_text="Entity name if available", null=True
            ),
        ),
        migrations.AlterField(
            model_name="afmentity",
            name="total_appearances",
            field=models.PositiveIntegerField(
                default=0, help_text="Total number of times this AFM has appeared"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="auto_registered",
            field=models.BooleanField(
                blank=True,
                help_text="Whether the company is auto-registered",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="city",
            field=models.CharField(
                blank=True, help_text="City", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Creation timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(
                blank=True, help_text="Company email", max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="gemi_office_id",
            field=models.IntegerField(
                blank=True, help_text="GEMI office ID", null=True
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="gemi_office_name",
            field=models.CharField(
                blank=True, help_text="GEMI office name", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="incorporation_date",
            field=models.CharField(
                blank=True, help_text="Incorporation date", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="is_branch",
            field=models.BooleanField(
                blank=True, help_text="Whether this is a branch", null=True
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="last_status_change",
            field=models.CharField(
                blank=True,
                help_text="Last status change date",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="legal_type_id",
            field=models.IntegerField(blank=True, help_text="Legal type ID", null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="legal_type_name",
            field=models.CharField(
                blank=True, help_text="Legal type name", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="municipality_id",
            field=models.IntegerField(
                blank=True, help_text="Municipality ID", null=True
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="municipality_name",
            field=models.CharField(
                blank=True, help_text="Municipality name", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="po_box",
            field=models.CharField(
                blank=True, help_text="PO box", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="prefecture_id",
            field=models.IntegerField(blank=True, help_text="Prefecture ID", null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="prefecture_name",
            field=models.CharField(
                blank=True, help_text="Prefecture name", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="status_id",
            field=models.IntegerField(blank=True, help_text="Status ID", null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="status_name",
            field=models.CharField(
                blank=True, help_text="Status name", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="street",
            field=models.CharField(
                blank=True, help_text="Street", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="street_number",
            field=models.CharField(
                blank=True, help_text="Street number", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last update timestamp"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="url",
            field=models.URLField(blank=True, help_text="Company URL", null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="zip_code",
            field=models.CharField(
                blank=True, help_text="ZIP code", max_length=10, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="afmentity",
            index=models.Index(fields=["afm"], name="core_afment_afm_4cdc35_idx"),
        ),
        migrations.AddIndex(
            model_name="afmentity",
            index=models.Index(
                fields=["entity_type"], name="core_afment_entity__f5dcc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="afmentity",
            index=models.Index(
                fields=["gemi_lookup_attempted", "gemi_lookup_success"],
                name="core_afment_gemi_lo_6c472d_idx",
            ),
        ),
    ]
