# Generated by Django 5.2.3 on 2025-07-12 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_afmentity_error_count_afmentity_gemi_companies_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionAmountField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent_key_path",
                    models.CharField(
                        help_text="JSON path where amount was found, e.g., 'sponsor[0].expenseAmount'",
                        max_length=200,
                    ),
                ),
                (
                    "source_field_name",
                    models.CharField(
                        help_text="Field name, e.g., 'expenseAmount'", max_length=100
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=10)),
                (
                    "structure_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nested_object", "Nested Object"),
                            ("plain_numeric", "Plain Numeric"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "raw_context",
                    models.JSONField(
                        blank=True, help_text="Full JSON snippet for context", null=True
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amount_fields",
                        to="core.decision",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["decision", "amount"],
                        name="core_decisi_decisio_e83038_idx",
                    )
                ],
                "unique_together": {
                    ("decision", "parent_key_path", "source_field_name")
                },
            },
        ),
    ]
