# Generated by Django 5.2.3 on 2025-07-13 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_add_decision_amount_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="decisionamountfield",
            name="associated_relationship",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated entity relationship if this amount is tied to an entity",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_amounts",
                to="core.decisionentityrelationship",
            ),
        ),
        migrations.AddIndex(
            model_name="decisionamountfield",
            index=models.Index(
                fields=["associated_relationship", "amount"],
                name="core_decisi_associa_5bc459_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="decisionamountfield",
            index=models.Index(
                fields=["decision", "associated_relationship"],
                name="core_decisi_decisio_e6f166_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="decisionamountfield",
            index=models.Index(fields=["amount"], name="core_decisi_amount_c8c330_idx"),
        ),
    ]
