# Generated by Django 5.2.3 on 2025-08-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_decisionamountfield_associated_relationship_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="decisionamountfield",
            index=models.Index(
                condition=models.Q(("associated_relationship__isnull", False)),
                fields=["associated_relationship", "amount"],
                name="idx_linked_amounts_only",
            ),
        ),
        migrations.AddIndex(
            model_name="decisionentityrelationship",
            index=models.Index(
                fields=["decision"], name="core_decisi_decisio_6163ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="decisionentityrelationship",
            index=models.Index(
                fields=["entity"], name="core_decisi_entity__7f1f39_idx"
            ),
        ),
    ]
