# Generated by Django 5.2.6 on 2025-09-29 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_decisionamountfield_idx_linked_amounts_only_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtractorComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_before",
                    models.TextField(
                        blank=True, help_text="PYMUPDF extraction", null=True
                    ),
                ),
                (
                    "text_after",
                    models.TextField(
                        blank=True, help_text="DOCLING extraction", null=True
                    ),
                ),
                ("chars_before", models.IntegerField(blank=True, null=True)),
                ("chars_after", models.IntegerField(blank=True, null=True)),
                ("chars_diff", models.IntegerField(blank=True, null=True)),
                (
                    "pdf_path",
                    models.CharField(
                        blank=True,
                        help_text="Local path to downloaded PDF",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extractor_comparisons",
                        to="core.decision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extractor Comparison",
                "verbose_name_plural": "Extractor Comparisons",
            },
        ),
    ]
