# Generated by Django 5.2.6 on 2025-09-30 16:22

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_add_extractor_comparison"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionHealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision_issue_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Denormalized issue_date from Decision for efficient filtering",
                        null=True,
                    ),
                ),
                (
                    "overall_status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        db_index=True,
                        default="UNKNOWN",
                        help_text="Overall pipeline health status",
                        max_length=10,
                    ),
                ),
                (
                    "ingestion_status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        help_text="Decision saved to database with basic data",
                        max_length=10,
                    ),
                ),
                (
                    "relations_status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        help_text="Signers, units, organization properly linked",
                        max_length=10,
                    ),
                ),
                (
                    "entities_status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        help_text="AFM entities extracted and associated",
                        max_length=10,
                    ),
                ),
                (
                    "document_extraction_status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        help_text="Document downloaded and text extracted",
                        max_length=10,
                    ),
                ),
                (
                    "opensearch_status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        help_text="Document indexed in OpenSearch and searchable",
                        max_length=10,
                    ),
                ),
                (
                    "coverage_status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        help_text="DateCoverage records updated",
                        max_length=10,
                    ),
                ),
                (
                    "findings",
                    models.JSONField(
                        default=dict,
                        help_text="Detailed findings and error messages for each component",
                    ),
                ),
                ("last_checked_at", models.DateTimeField(auto_now=True)),
                (
                    "check_duration_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Time taken to perform the health check in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "has_errors",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if any component has ERROR status",
                    ),
                ),
                (
                    "has_warnings",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if any component has WARNING status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.OneToOneField(
                        help_text="The decision being monitored",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_check",
                        to="core.decision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Decision Health Check",
                "verbose_name_plural": "Decision Health Checks",
                "indexes": [
                    models.Index(
                        fields=["overall_status"], name="core_decisi_overall_23e59b_idx"
                    ),
                    models.Index(
                        fields=["last_checked_at"],
                        name="core_decisi_last_ch_d70968_idx",
                    ),
                    models.Index(
                        fields=["has_errors", "has_warnings"],
                        name="core_decisi_has_err_085414_idx",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["findings"], name="core_decisi_finding_54c75e_gin"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DecisionHealthSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("total_decisions", models.IntegerField(default=0)),
                ("healthy_decisions", models.IntegerField(default=0)),
                ("warning_decisions", models.IntegerField(default=0)),
                ("error_decisions", models.IntegerField(default=0)),
                ("unknown_decisions", models.IntegerField(default=0)),
                ("ingestion_errors", models.IntegerField(default=0)),
                ("relations_errors", models.IntegerField(default=0)),
                ("entities_errors", models.IntegerField(default=0)),
                ("document_extraction_errors", models.IntegerField(default=0)),
                ("opensearch_errors", models.IntegerField(default=0)),
                ("coverage_errors", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Decision Health Summary",
                "verbose_name_plural": "Decision Health Summaries",
                "indexes": [
                    models.Index(fields=["date"], name="core_decisi_date_ef4412_idx"),
                    models.Index(
                        fields=["last_updated"], name="core_decisi_last_up_78e9be_idx"
                    ),
                ],
                "unique_together": {("date", "organization")},
            },
        ),
    ]
