# Generated by Django 5.2.9 on 2025-12-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_populate_decision_issue_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Backup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("postgres", "PostgreSQL"),
                            ("opensearch", "OpenSearch"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("s3_key", models.CharField(blank=True, max_length=255, null=True)),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("logs", models.TextField(blank=True)),
                (
                    "snapshot_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Backup",
                "verbose_name_plural": "Backups",
                "ordering": ["-created_at"],
            },
        ),
    ]
