# Generated by Django 5.2.9 on 2025-12-30 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_backup"),
    ]

    operations = [
        migrations.AddField(
            model_name="decision",
            name="import_job",
            field=models.ForeignKey(
                blank=True,
                help_text="The import batch (ImportJob) that created/updated this decision",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decisions",
                to="core.importjob",
            ),
        ),
    ]
