# Generated by Django 5.2.9 on 2025-12-31 14:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_decision_import_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIJobDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique name for this job (e.g., 'daily_summary')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name (e.g., 'Daily Document Summary')",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of what this job does"
                    ),
                ),
                (
                    "default_provider",
                    models.CharField(
                        help_text="Default provider (e.g., 'AWS_BEDROCK', 'OPENAI')",
                        max_length=50,
                    ),
                ),
                (
                    "default_model",
                    models.CharField(help_text="Default model name", max_length=100),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        help_text="Type of analysis (e.g., 'summary', 'classification', 'ranking')",
                        max_length=50,
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True,
                        help_text="System/instruction prompt template",
                        null=True,
                    ),
                ),
                (
                    "prompt_overhead_tokens",
                    models.IntegerField(
                        blank=True,
                        help_text="Fixed token count for prompts (if not using percentage)",
                        null=True,
                    ),
                ),
                (
                    "prompt_overhead_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Percentage overhead for prompts (e.g., 0.05 for 5%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "output_estimation_mode",
                    models.CharField(
                        choices=[
                            ("RATIO", "Ratio of Input"),
                            ("FIXED", "Fixed Token Count"),
                            ("PER_ITEM", "Fixed per Item"),
                        ],
                        default="RATIO",
                        max_length=20,
                    ),
                ),
                (
                    "output_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Output as ratio of input (e.g., 0.20 for 20%)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "fixed_output_tokens",
                    models.IntegerField(
                        blank=True, help_text="Fixed output token count", null=True
                    ),
                ),
                (
                    "batch_size",
                    models.IntegerField(
                        default=1,
                        help_text="How many items to process per API call (e.g., 3 for ranking)",
                    ),
                ),
                (
                    "items_per_batch_context",
                    models.TextField(
                        blank=True,
                        help_text="Description of how batching works (e.g., '3 summaries at a time')",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this job definition is active",
                    ),
                ),
                (
                    "max_concurrent_executions",
                    models.IntegerField(
                        default=1, help_text="Maximum concurrent executions allowed"
                    ),
                ),
                (
                    "extra_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional configuration parameters in JSON format",
                    ),
                ),
                (
                    "algorithm_module",
                    models.CharField(
                        blank=True,
                        help_text="Python module path for the job implementation (e.g., 'core.jobs.daily_summary')",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "algorithm_class",
                    models.CharField(
                        blank=True,
                        help_text="Class name that implements this job",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Job Definition",
                "verbose_name_plural": "AI Job Definitions",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="TaskOutputEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of task (e.g., 'summary', 'entities', 'classification')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "output_ratio",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Expected output tokens as ratio of input tokens (e.g., 0.15 for 15%)",
                        max_digits=5,
                    ),
                ),
                (
                    "fixed_output_tokens",
                    models.IntegerField(
                        blank=True,
                        help_text="Fixed output token count if not ratio-based",
                        null=True,
                    ),
                ),
                (
                    "prompt_overhead_ratio",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.10"),
                        help_text="Additional tokens added for system prompts (e.g., 0.10 for 10%)",
                        max_digits=5,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this task type includes",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Task Output Estimate",
                "verbose_name_plural": "Task Output Estimates",
                "ordering": ["task_type"],
            },
        ),
        migrations.AddField(
            model_name="documentanalysis",
            name="actual_cost_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Actual cost if reported by API in USD",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="documentanalysis",
            name="estimated_cost_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Estimated total cost in USD",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="documentanalysis",
            name="input_tokens",
            field=models.IntegerField(
                blank=True, help_text="Actual or estimated input tokens used", null=True
            ),
        ),
        migrations.AddField(
            model_name="documentanalysis",
            name="output_tokens",
            field=models.IntegerField(
                blank=True,
                help_text="Actual or estimated output tokens generated",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="documentembedding",
            name="estimated_cost_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Estimated cost for this embedding in USD",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="documentembedding",
            name="input_tokens",
            field=models.IntegerField(
                blank=True, help_text="Tokens used for embedding generation", null=True
            ),
        ),
        migrations.AlterField(
            model_name="documentanalysis",
            name="provider",
            field=models.CharField(
                choices=[
                    ("PYMUPDF", "PyMuPDF"),
                    ("PLAINTEXT", "Plain Text"),
                    ("DOCLING", "Docling"),
                    ("PYPDF", "PyPDF"),
                    ("PDFMINER", "PDF Miner"),
                    ("TESSERACT", "Tesseract OCR"),
                    ("GOOGLE_VISION", "Google Vision API"),
                    ("AZURE_OCR", "Azure OCR"),
                    ("OPENAI", "OpenAI"),
                    ("ANTHROPIC", "Anthropic Claude"),
                    ("GOOGLE_VERTEX", "Google Vertex AI"),
                    ("AWS_BEDROCK", "AWS Bedrock"),
                    ("MISTRAL", "Mistral AI"),
                    ("OLLAMA", "Ollama Local Models"),
                    ("OPENAI_EMBED", "OpenAI Embeddings"),
                    ("GOOGLE_EMBED", "Google Embeddings"),
                    ("SENTENCE_TRANSFORMERS", "Sentence Transformers"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="documentembedding",
            name="embedding_provider",
            field=models.CharField(
                choices=[
                    ("PYMUPDF", "PyMuPDF"),
                    ("PLAINTEXT", "Plain Text"),
                    ("DOCLING", "Docling"),
                    ("PYPDF", "PyPDF"),
                    ("PDFMINER", "PDF Miner"),
                    ("TESSERACT", "Tesseract OCR"),
                    ("GOOGLE_VISION", "Google Vision API"),
                    ("AZURE_OCR", "Azure OCR"),
                    ("OPENAI", "OpenAI"),
                    ("ANTHROPIC", "Anthropic Claude"),
                    ("GOOGLE_VERTEX", "Google Vertex AI"),
                    ("AWS_BEDROCK", "AWS Bedrock"),
                    ("MISTRAL", "Mistral AI"),
                    ("OLLAMA", "Ollama Local Models"),
                    ("OPENAI_EMBED", "OpenAI Embeddings"),
                    ("GOOGLE_EMBED", "Google Embeddings"),
                    ("SENTENCE_TRANSFORMERS", "Sentence Transformers"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="documentextraction",
            name="extraction_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PYMUPDF", "PyMuPDF"),
                    ("PLAINTEXT", "Plain Text"),
                    ("DOCLING", "Docling"),
                    ("PYPDF", "PyPDF"),
                    ("PDFMINER", "PDF Miner"),
                    ("TESSERACT", "Tesseract OCR"),
                    ("GOOGLE_VISION", "Google Vision API"),
                    ("AZURE_OCR", "Azure OCR"),
                    ("OPENAI", "OpenAI"),
                    ("ANTHROPIC", "Anthropic Claude"),
                    ("GOOGLE_VERTEX", "Google Vertex AI"),
                    ("AWS_BEDROCK", "AWS Bedrock"),
                    ("MISTRAL", "Mistral AI"),
                    ("OLLAMA", "Ollama Local Models"),
                    ("OPENAI_EMBED", "OpenAI Embeddings"),
                    ("GOOGLE_EMBED", "Google Embeddings"),
                    ("SENTENCE_TRANSFORMERS", "Sentence Transformers"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="AIJobExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "execution_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for this execution",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("provider_used", models.CharField(max_length=50)),
                ("model_used", models.CharField(max_length=100)),
                (
                    "items_processed",
                    models.IntegerField(
                        default=0,
                        help_text="Number of items processed (e.g., documents, summaries)",
                    ),
                ),
                (
                    "items_scope",
                    models.JSONField(
                        blank=True,
                        help_text="IDs or identifiers of items in scope",
                        null=True,
                    ),
                ),
                (
                    "estimated_cost_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Pre-execution cost estimate",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "actual_cost_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Actual cost based on token usage",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("total_input_tokens", models.IntegerField(default=0)),
                ("total_output_tokens", models.IntegerField(default=0)),
                (
                    "result_summary",
                    models.JSONField(
                        blank=True, help_text="Summary of results", null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "execution_time_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Total execution time in seconds",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="core.aijobdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Job Execution",
                "verbose_name_plural": "AI Job Executions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AIJobExecutionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        help_text="Type of item (e.g., 'DocumentExtraction', 'DocumentAnalysis')",
                        max_length=50,
                    ),
                ),
                (
                    "item_id",
                    models.IntegerField(help_text="ID of the item being processed"),
                ),
                (
                    "item_identifier",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable identifier (e.g., ADA number)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "sequence_number",
                    models.IntegerField(
                        help_text="Order in which this item was processed"
                    ),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "actual_cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(
                        blank=True,
                        help_text="Result data for this item (e.g., generated summary)",
                        null=True,
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "created_analysis",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to DocumentAnalysis created by this job item",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_execution_items",
                        to="core.documentanalysis",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.aijobexecution",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Job Execution Item",
                "verbose_name_plural": "AI Job Execution Items",
                "ordering": ["execution", "sequence_number"],
            },
        ),
        migrations.CreateModel(
            name="AIModelPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        db_index=True,
                        help_text="Provider name (e.g., OPENAI, ANTHROPIC, GOOGLE_VERTEX)",
                        max_length=50,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        db_index=True,
                        help_text="Specific model name (e.g., gpt-4-turbo, claude-3-opus)",
                        max_length=100,
                    ),
                ),
                (
                    "pricing_unit",
                    models.CharField(
                        choices=[
                            ("PER_MILLION", "Per Million Tokens"),
                            ("PER_THOUSAND", "Per Thousand Tokens"),
                        ],
                        default="PER_MILLION",
                        help_text="Unit for pricing (OpenAI/Anthropic use million, AWS Bedrock uses thousand)",
                        max_length=20,
                    ),
                ),
                (
                    "input_price",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Price per unit for input tokens (in USD)",
                        max_digits=10,
                    ),
                ),
                (
                    "output_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Price per unit for output tokens (in USD). Null for embeddings.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("CHAT", "Chat/Completion"),
                            ("EMBEDDING", "Embedding"),
                        ],
                        db_index=True,
                        default="CHAT",
                        max_length=20,
                    ),
                ),
                (
                    "context_window",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum context window in tokens",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this pricing is currently active",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="Date when this pricing became/becomes effective"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about pricing, special rates, etc.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Model Pricing",
                "verbose_name_plural": "AI Model Pricing",
                "ordering": ["-effective_date", "provider", "model_name"],
                "indexes": [
                    models.Index(
                        fields=["provider", "model_name", "is_active"],
                        name="core_aimode_provide_5aa296_idx",
                    ),
                    models.Index(
                        fields=["model_type", "is_active"],
                        name="core_aimode_model_t_065e3b_idx",
                    ),
                    models.Index(
                        fields=["effective_date"], name="core_aimode_effecti_ecdb93_idx"
                    ),
                ],
                "unique_together": {("provider", "model_name", "effective_date")},
            },
        ),
        migrations.AddIndex(
            model_name="aijobexecution",
            index=models.Index(
                fields=["job_definition", "status"],
                name="core_aijobe_job_def_af89f8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aijobexecution",
            index=models.Index(
                fields=["started_at"], name="core_aijobe_started_d2475a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aijobexecution",
            index=models.Index(fields=["status"], name="core_aijobe_status_cb64ad_idx"),
        ),
        migrations.AddIndex(
            model_name="aijobexecutionitem",
            index=models.Index(
                fields=["execution", "sequence_number"],
                name="core_aijobe_executi_7290cb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aijobexecutionitem",
            index=models.Index(
                fields=["item_type", "item_id"], name="core_aijobe_item_ty_941a8a_idx"
            ),
        ),
    ]
