# Generated by Django 5.2.9 on 2025-12-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_aijobdefinition_taskoutputestimate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodelpricing",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Human-friendly name (e.g., 'Claude Haiku 3', 'GPT-4 Turbo'). If empty, model_name is used.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="aimodelpricing",
            name="model_name",
            field=models.CharField(
                db_index=True,
                help_text="Actual model identifier used in API calls (e.g., 'anthropic.claude-3-haiku-20240307-v1:0', 'gpt-4-turbo-2024-04-09')",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="aimodelpricing",
            name="provider",
            field=models.CharField(
                db_index=True,
                help_text="Provider name (e.g., OPENAI, ANTHROPIC, AWS_BEDROCK)",
                max_length=50,
            ),
        ),
    ]
