# Generated by Django 5.2.9 on 2026-01-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_aimodelpricing_display_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AFMFetchJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("afm", models.CharField(db_index=True, max_length=9)),
                ("task_id", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("parent_ada", models.CharField(blank=True, max_length=100, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "afm_fetch_jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["afm", "status"], name="afm_fetch_j_afm_85cf21_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="afm_fetch_j_status_d87a9a_idx",
                    ),
                ],
            },
        ),
    ]
