# Generated by Django 5.2.9 on 2026-01-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_afmfetchjob"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="afmfetchjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "in_progress"])),
                fields=("afm",),
                name="unique_active_afm_fetch",
            ),
        ),
    ]
