# Generated by Django 5.2.9 on 2026-01-03 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_add_unique_active_afm_constraint"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AFMFetchJob",
        ),
    ]
