# Generated by Django 5.2.9 on 2026-01-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_remove_afmfetchjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="decisionhealthcheck",
            name="import_status",
            field=models.CharField(
                choices=[
                    ("HEALTHY", "Healthy"),
                    ("WARNING", "Warning"),
                    ("ERROR", "Error"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                help_text="Decision imported from DTO to database with all relations",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="decisionhealthcheck",
            name="organization_status",
            field=models.CharField(
                choices=[
                    ("HEALTHY", "Healthy"),
                    ("WARNING", "Warning"),
                    ("ERROR", "Error"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                help_text="Organization resolution completed for signers and units",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="decisionhealthcheck",
            name="ingestion_status",
            field=models.CharField(
                choices=[
                    ("HEALTHY", "Healthy"),
                    ("WARNING", "Warning"),
                    ("ERROR", "Error"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="UNKNOWN",
                help_text="Decision exists in database (legacy field, use import_status)",
                max_length=10,
            ),
        ),
    ]
