# Generated by Django 5.2.9 on 2026-01-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_add_import_and_organization_status_to_health_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="decision",
            name="discovery_sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Tracks how this decision was discovered. List of source objects with source_type (default/org-specific/unit-specific/etc) and search_params.",
                verbose_name="Discovery Sources",
            ),
        ),
        migrations.AddField(
            model_name="decision",
            name="first_discovery_source",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="The type of the first source that discovered this decision",
                max_length=50,
                null=True,
                verbose_name="First Discovery Source",
            ),
        ),
        migrations.AlterField(
            model_name="decisionentityrelationship",
            name="role",
            field=models.CharField(
                choices=[
                    ("sponsorAFMName", "Sponsor"),
                    ("org", "Organization"),
                    ("person", "Person"),
                    ("grantor", "Grantor"),
                    ("grantee", "Grantee"),
                    ("donationGiver", "Donation Giver"),
                    ("donationReceiver", "Donation Receiver"),
                    ("contractor", "Contractor"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
