# Generated by Django 5.2.9 on 2026-01-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_add_decision_discovery_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decision",
            name="discovery_sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Tracks how this decision was discovered. List of source objects with source_type (default/org-specific/unit-specific/etc) and search_params.",
                null=True,
                verbose_name="Discovery Sources",
            ),
        ),
    ]
