# Generated by Django 5.2.9 on 2026-01-15 17:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_fix_discovery_sources_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="importjob",
            name="chunk_task_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                help_text="Celery task IDs for chunk processing",
                size=None,
                verbose_name="Chunk Task IDs",
            ),
        ),
        migrations.AddField(
            model_name="importjob",
            name="chunks_completed",
            field=models.IntegerField(default=0, verbose_name="Chunks Completed"),
        ),
        migrations.AddField(
            model_name="importjob",
            name="chunks_failed",
            field=models.IntegerField(default=0, verbose_name="Chunks Failed"),
        ),
        migrations.AddField(
            model_name="importjob",
            name="search_params",
            field=models.JSONField(
                blank=True,
                help_text="API search parameters used",
                null=True,
                verbose_name="Search Parameters",
            ),
        ),
        migrations.AddField(
            model_name="importjob",
            name="total_chunks",
            field=models.IntegerField(
                default=0,
                help_text="Number of Redis chunks created",
                verbose_name="Total Chunks",
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("fetching", "Fetching from API"),
                    ("splitting", "Splitting into chunks"),
                    ("processing", "Processing chunks"),
                    ("completed", "Completed"),
                    ("partially_completed", "Partially Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
