# Generated by Django 5.2.9 on 2026-01-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_importjob_chunk_task_ids_importjob_chunks_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="importjob",
            name="decisions_assigned_to_pipeline",
            field=models.IntegerField(
                default=0,
                help_text="Decisions dispatched to run_decision_pipeline_task",
                verbose_name="Assigned to Pipeline",
            ),
        ),
        migrations.AddField(
            model_name="importjob",
            name="decisions_restored_from_redis",
            field=models.IntegerField(
                default=0,
                help_text="Decisions loaded from Redis chunks",
                verbose_name="Restored from Redis",
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="total_decisions",
            field=models.IntegerField(
                default=0,
                help_text="Decisions fetched from API and stored in Redis",
                verbose_name="Total Decisions",
            ),
        ),
    ]
