# Generated by Django 5.2.9 on 2026-01-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_add_pipeline_progress_tracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable/disable the import validation system. Disable temporarily during maintenance or expected incomplete periods.",
                    ),
                ),
                (
                    "weekday_threshold",
                    models.PositiveIntegerField(
                        default=5000,
                        help_text="Minimum expected decisions for Monday-Friday (normal weekdays)",
                    ),
                ),
                (
                    "saturday_threshold",
                    models.PositiveIntegerField(
                        default=300, help_text="Minimum expected decisions for Saturday"
                    ),
                ),
                (
                    "sunday_threshold",
                    models.PositiveIntegerField(
                        default=100, help_text="Minimum expected decisions for Sunday"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about threshold adjustments (e.g., data range analyzed)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import Threshold Configuration",
                "verbose_name_plural": "Import Threshold Configuration",
                "db_table": "core_import_threshold",
            },
        ),
    ]
