# Generated by Django 5.2.9 on 2026-02-01 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_importthreshold"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(db_index=True, max_length=50)),
                (
                    "ada",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                (
                    "failure_type",
                    models.CharField(
                        choices=[
                            ("CHUNK", "Chunk Level Failure"),
                            ("DECISION", "Individual Decision Failure"),
                            ("FETCH", "API Fetch Failure"),
                        ],
                        default="DECISION",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField()),
                ("error_traceback", models.TextField(blank=True, null=True)),
                ("data_snapshot", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "import_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="failures",
                        to="core.importjob",
                        verbose_name="Import Job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import Failure",
                "verbose_name_plural": "Import Failures",
                "ordering": ["-created_at"],
            },
        ),
    ]
