# Generated by Django 5.2.9 on 2026-03-01 15:39

from django.db import migrations, models


# This migration was created because the Diavgeia API returns ExtraField DTOs
# with type=None for certain fields. This caused IntegrityError when trying
# to insert these fields into the database due to the NOT NULL constraint.
#
# Example problematic data from API (type_details for uid='Β.6'):
# ---------------------------------------------------------------------------
# TypeDetails(
#     uid='Β.6',
#     label='ΠΡΟΓΡΑΜΜΑΤΙΚΗ ΣΥΜΦΩΝΙΑ ΟΙΚΟΝΟΜΙΚΗΣ ΥΠΟΣΤΗΡΙΞΗΣ',
#     extraFields=[
#         ExtraField(uid='financialYear', type='integer', ...),  # OK
#         ExtraField(uid='investAmount', type='number', ...),    # OK
#         ExtraField(uid='signDate', type=None, ...),            # PROBLEM: type is None
#         ExtraField(uid='signExpireDate', type=None, ...),      # PROBLEM: type is None
#         ...
#     ]
# )
#
# The API returns None for type on date fields and possibly others.
# This migration allows NULL values in field_type to accommodate this API behavior.
# ---------------------------------------------------------------------------


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_importfailure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrafield",
            name="field_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("string", "String"),
                    ("number", "Number"),
                    ("integer", "Integer"),
                    ("boolean", "Boolean"),
                    ("object", "Object"),
                    ("date", "Date"),
                    ("monetary", "Monetary"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
