# Generated by Django 5.2.12 on 2026-04-04 08:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_fix_extra_field_type_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for the feature flag (e.g., 'STEALTH_MODE')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True, help_text="Enable or disable this feature"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("authentication", "Authentication & Access"),
                            ("data_indexing", "Data Indexing"),
                            ("data_extraction", "Data Extraction"),
                            ("data_enrichment", "Data Enrichment"),
                            ("api", "API Features"),
                            ("frontend", "Frontend Features"),
                            ("system", "System Features"),
                        ],
                        default="system",
                        help_text="Category for organizing flags",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this flag", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of what this flag controls"
                    ),
                ),
                (
                    "default_value",
                    models.BooleanField(
                        default=False,
                        help_text="Default value if not set in database or environment",
                    ),
                ),
                (
                    "env_var_name",
                    models.CharField(
                        blank=True,
                        help_text="Associated environment variable name (if applicable)",
                        max_length=100,
                    ),
                ),
                (
                    "requires_restart",
                    models.BooleanField(
                        default=False,
                        help_text="Whether changing this flag requires a service restart",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_checked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this flag was checked",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this flag is currently active in the system",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or warnings about this flag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Flag",
                "verbose_name_plural": "Feature Flags",
                "db_table": "core_feature_flags",
                "ordering": ["category", "key"],
                "indexes": [
                    models.Index(
                        fields=["key", "is_active"], name="core_featur_key_ba7734_idx"
                    ),
                    models.Index(
                        fields=["category"], name="core_featur_categor_3bf243_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FeatureFlagAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "changed_by",
                    models.CharField(
                        help_text="User or system that made the change", max_length=200
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("enabled", "Enabled"),
                            ("disabled", "Disabled"),
                            ("updated", "Updated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("old_value", models.BooleanField(blank=True, null=True)),
                ("new_value", models.BooleanField(blank=True, null=True)),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                (
                    "feature_flag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="core.featureflag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Flag Audit Log",
                "verbose_name_plural": "Feature Flag Audit Logs",
                "db_table": "core_feature_flag_audit_logs",
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["feature_flag", "-changed_at"],
                        name="core_featur_feature_a715db_idx",
                    )
                ],
            },
        ),
    ]
