# Generated by Django 5.2.12 on 2026-04-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_featureflag_featureflagauditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggestion_type",
                    models.CharField(
                        choices=[
                            ("organization", "Organization"),
                            ("signer", "Signer"),
                            ("unit", "Unit"),
                            ("company", "Company"),
                            ("company_person", "Company Person"),
                        ],
                        help_text="Type of entity to suggest",
                        max_length=50,
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        help_text="UID of the entity (organization.uid, signer.uid, etc.)",
                        max_length=255,
                    ),
                ),
                (
                    "display_text",
                    models.CharField(
                        help_text="Text to display in the suggestion (automatically populated from entity)",
                        max_length=500,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Display order (lower numbers appear first)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this suggestion is currently active",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description or reason for featuring this entity",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "click_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this suggestion was clicked",
                    ),
                ),
                (
                    "last_clicked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this suggestion was clicked",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Search Suggestion",
                "verbose_name_plural": "Search Suggestions",
                "db_table": "core_search_suggestion",
                "ordering": ["order", "-click_count"],
                "indexes": [
                    models.Index(
                        fields=["suggestion_type", "is_active", "order"],
                        name="core_search_suggest_ff443a_idx",
                    ),
                    models.Index(
                        fields=["is_active", "order"],
                        name="core_search_is_acti_71097f_idx",
                    ),
                ],
            },
        ),
    ]
