# Generated by Django 5.2.12 on 2026-04-05 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_remove_searchsuggestion_display_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionClassification",
            fields=[
                (
                    "decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="classification",
                        serialize=False,
                        to="core.decision",
                    ),
                ),
                (
                    "is_direct_assignment",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Δ.1 decision below €37,200 threshold",
                    ),
                ),
                ("classifier_version", models.CharField(default="v1.0", max_length=50)),
                ("classified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["is_direct_assignment", "classified_at"],
                        include=("decision_id",),
                        name="direct_assignment_covering_idx",
                    ),
                    models.Index(
                        condition=models.Q(
                            ("is_direct_assignment", False),
                            ("classified_at__isnull", False),
                        ),
                        fields=["decision_id"],
                        name="needs_reclassification_idx",
                    ),
                ],
            },
        ),
    ]
