# Generated by Django 5.2.12 on 2026-04-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_decisionclassification"),
    ]

    operations = [
        migrations.AddField(
            model_name="featureflag",
            name="list_value",
            field=models.JSONField(
                blank=True,
                help_text="For list-type flags: array of values (e.g., ['Δ.1', 'Β.2.2'])",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="featureflag",
            name="string_value",
            field=models.TextField(
                blank=True, help_text="For string-type flags: text value"
            ),
        ),
        migrations.AddField(
            model_name="featureflag",
            name="value_type",
            field=models.CharField(
                choices=[
                    ("boolean", "Boolean (True/False)"),
                    ("list", "List (Multiple Values)"),
                    ("string", "String (Text)"),
                ],
                default="boolean",
                help_text="Type of value this flag stores",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="featureflag",
            name="category",
            field=models.CharField(
                choices=[
                    ("authentication", "Authentication & Access"),
                    ("data_indexing", "Data Indexing"),
                    ("data_extraction", "Data Extraction"),
                    ("data_enrichment", "Data Enrichment"),
                    ("data_ingestion", "Data Ingestion"),
                    ("api", "API Features"),
                    ("frontend", "Frontend Features"),
                    ("system", "System Features"),
                ],
                default="system",
                help_text="Category for organizing flags",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="featureflag",
            name="enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable or disable this feature (for boolean flags)",
            ),
        ),
    ]
