# Generated by Django 5.2.12 on 2026-04-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_add_value_types_to_feature_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="decisionclassification",
            name="detection_method",
            field=models.CharField(
                choices=[
                    ("METADATA", "Metadata (Type & Amount)"),
                    ("TEXT", "Text Content"),
                    ("BOTH", "Both Methods"),
                    ("NONE", "Not Detected"),
                ],
                db_index=True,
                default="NONE",
                help_text="How the direct assignment was detected",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="decisionclassification",
            name="classifier_version",
            field=models.CharField(default="v2.0", max_length=50),
        ),
    ]
