# Generated by Django 5.2.12 on 2026-04-27

from django.db import migrations


def convert_stealth_allowlist_to_list(apps, schema_editor):
    """
    Convert STEALTH_ALLOWLIST from boolean type to list type.
    
    This migration updates the existing STEALTH_ALLOWLIST feature flag:
    - Changes value_type from 'boolean' to 'list'
    - Initializes list_value to empty list
    - Preserves the enabled status in is_active field
    """
    FeatureFlag = apps.get_model('core', 'FeatureFlag')
    
    try:
        flag = FeatureFlag.objects.get(key='STEALTH_ALLOWLIST')
        
        # Update the flag to list type
        flag.value_type = 'list'
        flag.list_value = []  # Start with empty list
        flag.description = (
            'When enabled with STEALTH_MODE, only users with emails in this list can access the system. '
            'Select existing users or add email addresses manually.'
        )
        
        # Save changes
        flag.save(update_fields=['value_type', 'list_value', 'description'])
        
        print(f"✓ Converted STEALTH_ALLOWLIST from boolean to list type")
        
    except FeatureFlag.DoesNotExist:
        print("ℹ STEALTH_ALLOWLIST flag does not exist yet, skipping migration")
        pass


def reverse_conversion(apps, schema_editor):
    """
    Reverse the conversion - change back to boolean type.
    """
    FeatureFlag = apps.get_model('core', 'FeatureFlag')
    
    try:
        flag = FeatureFlag.objects.get(key='STEALTH_ALLOWLIST')
        
        # Revert to boolean type
        flag.value_type = 'boolean'
        flag.list_value = None
        flag.description = 'When enabled with STEALTH_MODE, only users in AllowedUser table can access the system'
        
        flag.save(update_fields=['value_type', 'list_value', 'description'])
        
        print(f"✓ Reverted STEALTH_ALLOWLIST back to boolean type")
        
    except FeatureFlag.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_add_detection_method_to_classification"),
    ]

    operations = [
        migrations.RunPython(
            convert_stealth_allowlist_to_list,
            reverse_code=reverse_conversion,
        ),
    ]
