# Generated by Django 5.2.13 on 2026-05-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_convert_stealth_allowlist_to_list"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="documentpage",
            name="core_docume_search__9e73d9_gin",
        ),
        migrations.RemoveField(
            model_name="documentpage",
            name="raw_text",
        ),
        migrations.RemoveField(
            model_name="documentpage",
            name="search_vector",
        ),
        migrations.AlterField(
            model_name="featureflag",
            name="value_type",
            field=models.CharField(
                choices=[
                    ("boolean", "Boolean (True/False)"),
                    ("list", "List (Multiple Values)"),
                    ("string", "String (Text)"),
                    ("choice", "Choice (String from Predefined List)"),
                ],
                default="boolean",
                help_text="Type of value this flag stores",
                max_length=20,
            ),
        ),
    ]
