# Generated by Django 5.2.13 on 2026-05-01 18:31

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_afmentity_search_vector_organization_search_vector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="companyperson",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
    ]
