# Generated by manual creation on 2026-05-01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_company_search_vector_companyperson_search_vector"),
    ]
    # Don't want afm included - only name
    operations = [
        # AFMEntity trigger and index
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION afmentity_search_vector_update() RETURNS trigger AS $$
            BEGIN
                NEW.search_vector = to_tsvector('greek', unaccent(
                    COALESCE(NEW.name, '')
                ));
                RETURN NEW;
            END
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS afmentity_search_vector_update ON core_afmentity;
            
            CREATE TRIGGER afmentity_search_vector_update
            BEFORE INSERT OR UPDATE OF name
            ON core_afmentity
            FOR EACH ROW
            EXECUTE FUNCTION afmentity_search_vector_update();
            
            CREATE INDEX IF NOT EXISTS core_afmentity_search_vector_idx 
            ON core_afmentity USING GIN(search_vector);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS core_afmentity_search_vector_idx;
            DROP TRIGGER IF EXISTS afmentity_search_vector_update ON core_afmentity;
            DROP FUNCTION IF EXISTS afmentity_search_vector_update();
            """,
        ),
        
        # Organization trigger and index
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION organization_search_vector_update() RETURNS trigger AS $$
            BEGIN
                NEW.search_vector = to_tsvector('greek', unaccent(
                    COALESCE(NEW.label, '')
                ));
                RETURN NEW;
            END
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS organization_search_vector_update ON core_organization;
            
            CREATE TRIGGER organization_search_vector_update
            BEFORE INSERT OR UPDATE OF label
            ON core_organization
            FOR EACH ROW
            EXECUTE FUNCTION organization_search_vector_update();
            
            CREATE INDEX IF NOT EXISTS core_organization_search_vector_idx 
            ON core_organization USING GIN(search_vector);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS core_organization_search_vector_idx;
            DROP TRIGGER IF EXISTS organization_search_vector_update ON core_organization;
            DROP FUNCTION IF EXISTS organization_search_vector_update();
            """,
        ),
        
        # Unit trigger and index
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION unit_search_vector_update() RETURNS trigger AS $$
            BEGIN
                NEW.search_vector = to_tsvector('greek', unaccent(
                    COALESCE(NEW.label, '')
                ));
                RETURN NEW;
            END
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS unit_search_vector_update ON core_unit;
            
            CREATE TRIGGER unit_search_vector_update
            BEFORE INSERT OR UPDATE OF label
            ON core_unit
            FOR EACH ROW
            EXECUTE FUNCTION unit_search_vector_update();
            
            CREATE INDEX IF NOT EXISTS core_unit_search_vector_idx 
            ON core_unit USING GIN(search_vector);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS core_unit_search_vector_idx;
            DROP TRIGGER IF EXISTS unit_search_vector_update ON core_unit;
            DROP FUNCTION IF EXISTS unit_search_vector_update();
            """,
        ),
        
        # Signer trigger and index
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION signer_search_vector_update() RETURNS trigger AS $$
            BEGIN
                NEW.search_vector = to_tsvector('greek', unaccent(
                    COALESCE(NEW.first_name, '') || ' ' ||
                    COALESCE(NEW.last_name, '')
                ));
                RETURN NEW;
            END
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS signer_search_vector_update ON core_signer;
            
            CREATE TRIGGER signer_search_vector_update
            BEFORE INSERT OR UPDATE OF first_name, last_name
            ON core_signer
            FOR EACH ROW
            EXECUTE FUNCTION signer_search_vector_update();
            
            CREATE INDEX IF NOT EXISTS core_signer_search_vector_idx 
            ON core_signer USING GIN(search_vector);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS core_signer_search_vector_idx;
            DROP TRIGGER IF EXISTS signer_search_vector_update ON core_signer;
            DROP FUNCTION IF EXISTS signer_search_vector_update();
            """,
        ),
        
        # companies trigger and index
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION companies_search_vector_update() RETURNS trigger AS $$
            BEGIN
                NEW.search_vector = to_tsvector('greek', unaccent(
                    COALESCE(NEW.co_name_el, '') || ' ' ||
                    COALESCE(array_to_string(NEW.co_names_en, ' '), '') || ' ' ||
                    COALESCE(array_to_string(NEW.co_titles_el, ' '), '') || ' ' ||
                    COALESCE(array_to_string(NEW.co_titles_en, ' '), '')
                ));
                RETURN NEW;
            END
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS companies_search_vector_update ON companies;
            
            CREATE TRIGGER companies_search_vector_update
            BEFORE INSERT OR UPDATE OF co_name_el, co_names_en, co_titles_el, co_titles_en
            ON companies
            FOR EACH ROW
            EXECUTE FUNCTION companies_search_vector_update();
            
            CREATE INDEX IF NOT EXISTS companies_search_vector_idx 
            ON companies USING GIN(search_vector);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS companies_search_vector_idx;
            DROP TRIGGER IF EXISTS companies_search_vector_update ON companies;
            DROP FUNCTION IF EXISTS companies_search_vector_update();
            """,
        ),
        
        # companiesPerson trigger and index
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION company_person_search_vector_update() RETURNS trigger AS $$
            BEGIN
                NEW.search_vector = to_tsvector('greek', unaccent(
                    COALESCE(NEW.person_name, '')
                ));
                RETURN NEW;
            END
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS company_person_search_vector_update ON company_persons;
            
            CREATE TRIGGER company_person_search_vector_update
            BEFORE INSERT OR UPDATE OF person_name
            ON company_persons
            FOR EACH ROW
            EXECUTE FUNCTION company_person_search_vector_update();
            
            CREATE INDEX IF NOT EXISTS company_persons_search_vector_idx 
            ON company_persons USING GIN(search_vector);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS company_persons_search_vector_idx;
            DROP TRIGGER IF EXISTS company_person_search_vector_update ON company_persons;
            DROP FUNCTION IF EXISTS company_person_search_vector_update();
            """,
        ),
    ]
