# Generated by Django 5.2.13 on 2026-05-07 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_add_search_vector_triggers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassificationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "processing_mode",
                    models.CharField(
                        choices=[
                            ("unclassified", "Unclassified Decisions"),
                            ("date_range", "Date Range"),
                            ("reclassify", "Re-classify (Algorithm Update)"),
                            ("outdated", "Outdated Classifier Version"),
                            ("all", "All Decisions"),
                        ],
                        default="unclassified",
                        help_text="Which decisions to classify",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Start date for date_range mode",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="End date for date_range mode", null=True
                    ),
                ),
                (
                    "batch_size",
                    models.PositiveIntegerField(
                        default=1000,
                        help_text="Number of decisions to process per batch",
                    ),
                ),
                (
                    "reclassify",
                    models.BooleanField(
                        default=False,
                        help_text="Re-classify even if already classified",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("running", "RUNNING"),
                            ("paused", "PAUSED"),
                            ("completed", "COMPLETED"),
                            ("failed", "FAILED"),
                            ("cancelled", "CANCELLED"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery task ID for tracking",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "total_decisions",
                    models.PositiveIntegerField(
                        default=0, help_text="Total decisions to process"
                    ),
                ),
                (
                    "processed_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Decisions processed so far"
                    ),
                ),
                (
                    "direct_assignments_found",
                    models.PositiveIntegerField(
                        default=0, help_text="Direct assignments identified"
                    ),
                ),
                (
                    "non_direct_assignments",
                    models.PositiveIntegerField(
                        default=0, help_text="Non-direct assignments"
                    ),
                ),
                (
                    "created_count",
                    models.PositiveIntegerField(
                        default=0, help_text="New classifications created"
                    ),
                ),
                (
                    "updated_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Existing classifications updated"
                    ),
                ),
                (
                    "error_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Errors encountered"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When processing started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When processing completed", null=True
                    ),
                ),
                (
                    "estimated_completion",
                    models.DateTimeField(
                        blank=True, help_text="Estimated completion time", null=True
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, help_text="Last error message if failed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="classification_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassificationJobLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("level", models.CharField(default="INFO", max_length=20)),
                ("message", models.TextField()),
                ("batch_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "decisions_in_batch",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="core.classificationjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="classificationjob",
            index=models.Index(
                fields=["status", "created_at"], name="core_classi_status_790b73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classificationjob",
            index=models.Index(
                fields=["created_by", "status"], name="core_classi_created_d4d513_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classificationjoblog",
            index=models.Index(
                fields=["job", "timestamp"], name="core_classi_job_id_aa559e_idx"
            ),
        ),
    ]
