# Generated by Django 5.2.13 on 2026-05-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_classificationjob_classificationjoblog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classificationjob",
            name="max_decisions",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum number of decisions to process (leave empty for unlimited)",
                null=True,
            ),
        ),
    ]
