# Generated by Django 5.2.13 on 2026-05-14 10:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_classificationjob_max_decisions"),
    ]

    operations = [
        migrations.CreateModel(
            name="AFMScoringConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name for this scoring configuration (e.g., 'Default', 'Aggressive', 'Conservative')",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one config can be active at a time",
                    ),
                ),
                (
                    "frequency_weight",
                    models.FloatField(
                        default=0.3,
                        help_text="Weight for appearance frequency (0-1)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "amount_weight",
                    models.FloatField(
                        default=0.5,
                        help_text="Weight for total transaction amounts (0-1)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "organization_weight",
                    models.FloatField(
                        default=0.2,
                        help_text="Weight for unique organization count (0-1)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "min_appearances",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Minimum number of decision appearances to be eligible for fetching",
                    ),
                ),
                (
                    "min_total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=5000.0,
                        help_text="Minimum total transaction amount (€) to be eligible",
                        max_digits=15,
                    ),
                ),
                (
                    "min_unique_organizations",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Minimum number of unique organizations worked with",
                    ),
                ),
                (
                    "retry_failed_after_days",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="Days to wait before retrying a failed GEMI lookup",
                    ),
                ),
                (
                    "never_retry_after_failures",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Stop retrying after this many consecutive failures",
                    ),
                ),
                (
                    "enable_recency_boost",
                    models.BooleanField(
                        default=False,
                        help_text="Boost score for entities seen recently",
                    ),
                ),
                (
                    "recency_days_threshold",
                    models.PositiveIntegerField(
                        default=30, help_text="Days threshold for recency boost"
                    ),
                ),
                (
                    "recency_boost_multiplier",
                    models.FloatField(
                        default=1.2,
                        help_text="Multiplier for recent entities (e.g., 1.2 = 20% boost)",
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(3.0),
                        ],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about this configuration"
                    ),
                ),
            ],
            options={
                "verbose_name": "AFM Scoring Configuration",
                "verbose_name_plural": "AFM Scoring Configurations",
                "ordering": ["-is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="AFMEntityScore",
            fields=[
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="score_data",
                        serialize=False,
                        to="core.afmentity",
                    ),
                ),
                (
                    "total_score",
                    models.FloatField(
                        db_index=True,
                        default=0.0,
                        help_text="Final weighted score (0-100)",
                    ),
                ),
                (
                    "frequency_score",
                    models.FloatField(
                        default=0.0, help_text="Normalized appearance frequency score"
                    ),
                ),
                (
                    "amount_score",
                    models.FloatField(
                        default=0.0, help_text="Normalized total amount score"
                    ),
                ),
                (
                    "organization_score",
                    models.FloatField(
                        default=0.0, help_text="Normalized unique organization score"
                    ),
                ),
                (
                    "total_appearances",
                    models.PositiveIntegerField(
                        default=0, help_text="Total decision appearances"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Sum of all associated transaction amounts",
                        max_digits=20,
                    ),
                ),
                (
                    "unique_organizations",
                    models.PositiveIntegerField(
                        default=0, help_text="Count of unique organizations"
                    ),
                ),
                (
                    "is_eligible",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Meets minimum thresholds for fetching",
                    ),
                ),
                (
                    "fetch_priority",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Priority rank (1 = highest priority)",
                    ),
                ),
                (
                    "scored_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this score was last computed"
                    ),
                ),
                (
                    "config_used",
                    models.ForeignKey(
                        help_text="Configuration used to compute this score",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.afmscoringconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "AFM Entity Score",
                "verbose_name_plural": "AFM Entity Scores",
                "ordering": ["-total_score"],
                "indexes": [
                    models.Index(
                        fields=["-total_score"], name="core_afment_total_s_73cc59_idx"
                    ),
                    models.Index(
                        fields=["is_eligible", "-total_score"],
                        name="core_afment_is_elig_5d5576_idx",
                    ),
                    models.Index(
                        fields=["fetch_priority"], name="core_afment_fetch_p_28e769_idx"
                    ),
                ],
            },
        ),
    ]
