# Generated by Django 5.2.13 on 2026-05-14 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_afmscoringconfig_afmentityscore"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AFMScoringJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "batch_size",
                    models.PositiveIntegerField(
                        default=1000,
                        help_text="Number of entities to process per batch",
                    ),
                ),
                (
                    "exclude_already_fetched",
                    models.BooleanField(
                        default=False,
                        help_text="Exclude entities with successful GEMI data",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("running", "RUNNING"),
                            ("paused", "PAUSED"),
                            ("completed", "COMPLETED"),
                            ("failed", "FAILED"),
                            ("cancelled", "CANCELLED"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery task ID for tracking",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "total_entities",
                    models.PositiveIntegerField(
                        default=0, help_text="Total entities to process"
                    ),
                ),
                (
                    "processed_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Entities processed so far"
                    ),
                ),
                (
                    "scored_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Entities successfully scored"
                    ),
                ),
                (
                    "eligible_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Entities eligible for fetch"
                    ),
                ),
                (
                    "ineligible_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Entities not eligible for fetch"
                    ),
                ),
                (
                    "error_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Errors encountered"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When processing started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When processing completed", null=True
                    ),
                ),
                (
                    "estimated_completion",
                    models.DateTimeField(
                        blank=True, help_text="Estimated completion time", null=True
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, help_text="Last error message if failed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "config",
                    models.ForeignKey(
                        help_text="Scoring configuration to use",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scoring_jobs",
                        to="core.afmscoringconfig",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="afm_scoring_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AFM Scoring Job",
                "verbose_name_plural": "AFM Scoring Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AFMScoringJobLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("level", models.CharField(default="INFO", max_length=20)),
                ("message", models.TextField()),
                ("batch_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "entities_in_batch",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="core.afmscoringjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "AFM Scoring Job Log",
                "verbose_name_plural": "AFM Scoring Job Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="afmscoringjob",
            index=models.Index(
                fields=["status", "created_at"], name="core_afmsco_status_ca7ec5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="afmscoringjob",
            index=models.Index(
                fields=["created_by", "status"], name="core_afmsco_created_b7f78a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="afmscoringjoblog",
            index=models.Index(
                fields=["job", "timestamp"], name="core_afmsco_job_id_61b701_idx"
            ),
        ),
    ]
