# Generated by Django 5.2.13 on 2026-05-16 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_afm_scoring_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="afmentityscore",
            name="direct_assignment_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of times entity appeared in direct assignments",
            ),
        ),
        migrations.AddField(
            model_name="afmentityscore",
            name="direct_assignment_count_score",
            field=models.FloatField(
                default=0.0, help_text="Normalized direct assignment count score (0-1)"
            ),
        ),
        migrations.AddField(
            model_name="afmentityscore",
            name="direct_assignment_percentage",
            field=models.FloatField(
                default=0.0,
                help_text="Percentage of appearances that are direct assignments (0-100)",
            ),
        ),
        migrations.AddField(
            model_name="afmentityscore",
            name="direct_assignment_percentage_score",
            field=models.FloatField(
                default=0.0,
                help_text="Normalized direct assignment percentage score (0-1)",
            ),
        ),
        migrations.AddField(
            model_name="afmentityscore",
            name="normalization_stats",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Statistics used for normalization (for transparency/debugging)",
            ),
        ),
        migrations.AddField(
            model_name="afmscoringconfig",
            name="amount_impact",
            field=models.CharField(
                choices=[
                    ("POSITIVE", "Positive (higher is better)"),
                    ("NEGATIVE", "Negative (higher is worse)"),
                ],
                default="POSITIVE",
                help_text="Impact direction for amount (usually POSITIVE)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="afmscoringconfig",
            name="direct_assignment_count_impact",
            field=models.CharField(
                choices=[
                    ("POSITIVE", "Positive (higher is better)"),
                    ("NEGATIVE", "Negative (higher is worse)"),
                ],
                default="POSITIVE",
                help_text="Impact direction for direct assignment count (POSITIVE = more is better)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="afmscoringconfig",
            name="direct_assignment_count_weight",
            field=models.FloatField(
                default=0.2,
                help_text="Weight for number of direct assignments (0-1)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="afmscoringconfig",
            name="direct_assignment_percentage_impact",
            field=models.CharField(
                choices=[
                    ("POSITIVE", "Positive (higher is better)"),
                    ("NEGATIVE", "Negative (higher is worse)"),
                ],
                default="POSITIVE",
                help_text="Impact direction for direct assignment percentage (POSITIVE = higher % is better)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="afmscoringconfig",
            name="direct_assignment_percentage_weight",
            field=models.FloatField(
                default=0.2,
                help_text="Weight for percentage of appearances that are direct assignments (0-1)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="afmscoringconfig",
            name="frequency_impact",
            field=models.CharField(
                choices=[
                    ("POSITIVE", "Positive (higher is better)"),
                    ("NEGATIVE", "Negative (higher is worse)"),
                ],
                default="POSITIVE",
                help_text="Impact direction for frequency (usually POSITIVE)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="afmscoringconfig",
            name="min_direct_assignments",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Minimum number of direct assignments (0 = no minimum)",
            ),
        ),
        migrations.AddField(
            model_name="afmscoringconfig",
            name="normalization_strategy",
            field=models.CharField(
                choices=[
                    ("MIN_MAX", "Min-Max (0-1 range)"),
                    ("Z_SCORE", "Z-Score (standardization)"),
                    ("ROBUST", "Robust Scaling (median/IQR)"),
                    ("LOG", "Log Transform + Min-Max"),
                ],
                default="ROBUST",
                help_text="Normalization method for feature scaling",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="afmscoringconfig",
            name="organization_impact",
            field=models.CharField(
                choices=[
                    ("POSITIVE", "Positive (higher is better)"),
                    ("NEGATIVE", "Negative (higher is worse)"),
                ],
                default="POSITIVE",
                help_text="Impact direction for unique organizations (usually POSITIVE)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="afmentityscore",
            name="amount_score",
            field=models.FloatField(
                default=0.0, help_text="Normalized total amount score (0-1)"
            ),
        ),
        migrations.AlterField(
            model_name="afmentityscore",
            name="frequency_score",
            field=models.FloatField(
                default=0.0, help_text="Normalized appearance frequency score (0-1)"
            ),
        ),
        migrations.AlterField(
            model_name="afmentityscore",
            name="organization_score",
            field=models.FloatField(
                default=0.0, help_text="Normalized unique organization score (0-1)"
            ),
        ),
        migrations.AlterField(
            model_name="afmscoringconfig",
            name="amount_weight",
            field=models.FloatField(
                default=0.25,
                help_text="Weight for total transaction amounts (0-1)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="afmscoringconfig",
            name="frequency_weight",
            field=models.FloatField(
                default=0.2,
                help_text="Weight for appearance frequency (0-1)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="afmscoringconfig",
            name="organization_weight",
            field=models.FloatField(
                default=0.15,
                help_text="Weight for unique organization count (0-1)",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="afmentityscore",
            index=models.Index(
                fields=["direct_assignment_count"],
                name="core_afment_direct__d192ef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="afmentityscore",
            index=models.Index(
                fields=["direct_assignment_percentage"],
                name="core_afment_direct__8ed5a6_idx",
            ),
        ),
    ]
