# Generated by Django 5.2.13 on 2026-05-16 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_afmentityscore_direct_assignment_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="afmscoringconfig",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When this configuration was created",
            ),
        ),
        migrations.AddField(
            model_name="afmscoringconfig",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When this configuration was last updated"
            ),
        ),
    ]
