# Generated by Django 5.2.13 on 2026-05-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_fix_companies_search_vector_jsonb"),
    ]

    operations = [
        migrations.AddField(
            model_name="afmscoringconfig",
            name="use_simple_scoring",
            field=models.BooleanField(
                default=True,
                help_text="Use simple percentage-based scoring (faster) instead of sophisticated normalization",
            ),
        ),
        migrations.AlterField(
            model_name="afmscoringconfig",
            name="normalization_strategy",
            field=models.CharField(
                choices=[
                    ("MIN_MAX", "Min-Max (0-1 range)"),
                    ("Z_SCORE", "Z-Score (standardization)"),
                    ("ROBUST", "Robust Scaling (median/IQR)"),
                    ("LOG", "Log Transform + Min-Max"),
                ],
                default="ROBUST",
                help_text="Normalization method for feature scaling (only used if use_simple_scoring=False)",
                max_length=20,
            ),
        ),
    ]
