# Generated by Django 5.2.13 on 2026-05-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_afmscoringconfig_use_simple_scoring_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="backup",
            name="use_streaming",
            field=models.BooleanField(
                default=True,
                help_text="Use streaming backup to avoid disk space issues",
            ),
        ),
    ]
