# Generated by Django 5.2.13 on 2026-05-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_add_use_streaming_to_backup"),
    ]

    operations = [
        migrations.AddField(
            model_name="backup",
            name="celery_task_id",
            field=models.CharField(
                blank=True,
                help_text="Celery task ID for tracking/cancellation",
                max_length=255,
                null=True,
            ),
        ),
    ]
