# Generated by Django 5.2.14 on 2026-05-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_legaldocument_delete_syncstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="decision",
            name="publish_date_day",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Date portion of publish_timestamp in Athens timezone. Matches the from_date / to_date Diavgeia API parameters.",
                null=True,
                verbose_name="Publish Date (Day Only)",
            ),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["publish_date_day"], name="core_decisi_publish_683f5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["organization", "publish_date_day"],
                name="core_decisi_organiz_652bdb_idx",
            ),
        ),
    ]
