# Generated by Django 5.2.14 on 2026-06-03 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_documentextraction_search_vector_gin_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="AFMEntityStats",
            fields=[
                (
                    "entity",
                    models.OneToOneField(
                        help_text="The AFM entity these stats belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="stats",
                        serialize=False,
                        to="core.afmentity",
                    ),
                ),
                (
                    "total_decisions",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of distinct decisions this entity appears in",
                    ),
                ),
                (
                    "distinct_roles",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of distinct roles this entity has (e.g. sponsor, grantee)",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Sum of all linked amounts (EUR)",
                        max_digits=18,
                    ),
                ),
                (
                    "average_amount_per_decision",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Average amount per decision with amounts",
                        max_digits=15,
                    ),
                ),
                (
                    "max_single_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Largest single amount linked to this entity",
                        max_digits=15,
                    ),
                ),
                (
                    "distinct_organizations",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of distinct organizations the entity has done business with",
                    ),
                ),
                (
                    "distinct_counterpart_entities",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of other distinct AFM entities (co-participants in same decisions)",
                    ),
                ),
                (
                    "direct_assignment_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of decisions classified as direct assignments",
                    ),
                ),
                (
                    "direct_assignment_percentage",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage of total decisions that are direct assignments (0-100)",
                    ),
                ),
                (
                    "computed_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When these stats were last computed"
                    ),
                ),
            ],
            options={
                "verbose_name": "AFM Entity Stats",
                "verbose_name_plural": "AFM Entity Stats",
                "ordering": ["-total_amount"],
            },
        ),
    ]
