# Generated by Django 5.2.14 on 2026-06-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_afmentitystats"),
    ]

    operations = [
        migrations.AddField(
            model_name="legaldocument",
            name="title",
            field=models.CharField(
                default="",
                help_text="Display name shown in the footer, e.g. 'Terms of Service'",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="legaldocument",
            name="type",
            field=models.SlugField(
                default="",
                help_text="URL-safe identifier, e.g. 'tos', 'privacy', 'about'",
            ),
        ),
        migrations.AlterField(
            model_name="legaldocument",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("el", "Greek")], default="en", max_length=5
            ),
        ),
        migrations.AlterUniqueTogether(
            name="legaldocument",
            unique_together={("type", "language")},
        ),
    ]
