# Generated by Django 5.2.14 on 2026-06-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_add_publish_date_day_to_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchsuggestion",
            name="suggestion_type",
            field=models.CharField(
                choices=[
                    ("organization", "Organization"),
                    ("signer", "Signer"),
                    ("unit", "Unit"),
                    ("company", "Company"),
                    ("company_person", "Company Person"),
                    ("afmentity", "AFM Entity"),
                ],
                help_text="Type of entity to suggest",
                max_length=50,
            ),
        ),
    ]
