# Generated by Django 5.2.15 on 2026-06-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_alter_searchsuggestion_suggestion_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="importjob",
            name="import_type",
            field=models.CharField(
                choices=[
                    ("daily", "Daily (cron)"),
                    ("backfill", "Backfill (autofarming)"),
                ],
                default="daily",
                help_text="Daily (cron-triggered) vs backfill (autofarming historical dates)",
                max_length=20,
                verbose_name="Import Type",
            ),
        ),
    ]
