# Generated by Django 5.2.15 on 2026-07-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_add_browse_first_letter_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="afmentitystats",
            name="direct_assignment_30k_38k",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of direct-assignment decisions with total amount €30k-€38k (the maximum threshold for direct awards)",
            ),
        ),
        migrations.AddField(
            model_name="afmentitystats",
            name="payment_30k_38k",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of decisions where the entity received €30k-€38k (money-receiving roles only)",
            ),
        ),
    ]
