# Generated by Django 5.2.15 on 2026-07-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_add_30k_38k_entity_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="afmentitystats",
            name="total_received_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total amount from 'Β.2.2' (expenditure/payment) decisions (EUR). Always computed regardless of the act-type filter dropdown.",
                max_digits=18,
            ),
        ),
    ]
