# Generated by Django 5.2.15 on 2026-07-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_add_total_received_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("fetching", "Fetching from API"),
                    ("splitting", "Splitting into chunks"),
                    ("processing", "Processing chunks"),
                    ("completed", "Completed"),
                    ("partially_completed", "Partially Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
