# Generated by Django 5.2.15 on 2026-07-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_alter_importjob_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="afmentitystats",
            name="combined_rank",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Rank of the sum of individual ranks across total_received_amount, direct_assignment_30k_38k, and payment_30k_38k. 1 = best. Computed during stats recalculation.",
            ),
        ),
    ]
