# Generated by Django 5.2.16 on 2026-07-28 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_add_combined_rank"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("version", models.IntegerField(default=1)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "trigger_type",
                    models.CharField(
                        blank=True,
                        help_text='Grouping key, e.g. "notification_batch_summary".',
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pipeline Definition",
                "verbose_name_plural": "Pipeline Definitions",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="documentanalysis",
            name="provider",
            field=models.CharField(
                choices=[
                    ("PYMUPDF", "PyMuPDF"),
                    ("PLAINTEXT", "Plain Text"),
                    ("DOCLING", "Docling"),
                    ("PYPDF", "PyPDF"),
                    ("PDFMINER", "PDF Miner"),
                    ("TESSERACT", "Tesseract OCR"),
                    ("GOOGLE_VISION", "Google Vision API"),
                    ("AZURE_OCR", "Azure OCR"),
                    ("OPENAI", "OpenAI"),
                    ("ANTHROPIC", "Anthropic Claude"),
                    ("GOOGLE_VERTEX", "Google Vertex AI"),
                    ("AWS_BEDROCK", "AWS Bedrock"),
                    ("MISTRAL", "Mistral AI"),
                    ("OLLAMA", "Ollama Local Models"),
                    ("OPENROUTER", "OpenRouter"),
                    ("OPENAI_EMBED", "OpenAI Embeddings"),
                    ("GOOGLE_EMBED", "Google Embeddings"),
                    ("SENTENCE_TRANSFORMERS", "Sentence Transformers"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="documentembedding",
            name="embedding_provider",
            field=models.CharField(
                choices=[
                    ("PYMUPDF", "PyMuPDF"),
                    ("PLAINTEXT", "Plain Text"),
                    ("DOCLING", "Docling"),
                    ("PYPDF", "PyPDF"),
                    ("PDFMINER", "PDF Miner"),
                    ("TESSERACT", "Tesseract OCR"),
                    ("GOOGLE_VISION", "Google Vision API"),
                    ("AZURE_OCR", "Azure OCR"),
                    ("OPENAI", "OpenAI"),
                    ("ANTHROPIC", "Anthropic Claude"),
                    ("GOOGLE_VERTEX", "Google Vertex AI"),
                    ("AWS_BEDROCK", "AWS Bedrock"),
                    ("MISTRAL", "Mistral AI"),
                    ("OLLAMA", "Ollama Local Models"),
                    ("OPENROUTER", "OpenRouter"),
                    ("OPENAI_EMBED", "OpenAI Embeddings"),
                    ("GOOGLE_EMBED", "Google Embeddings"),
                    ("SENTENCE_TRANSFORMERS", "Sentence Transformers"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="documentextraction",
            name="extraction_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PYMUPDF", "PyMuPDF"),
                    ("PLAINTEXT", "Plain Text"),
                    ("DOCLING", "Docling"),
                    ("PYPDF", "PyPDF"),
                    ("PDFMINER", "PDF Miner"),
                    ("TESSERACT", "Tesseract OCR"),
                    ("GOOGLE_VISION", "Google Vision API"),
                    ("AZURE_OCR", "Azure OCR"),
                    ("OPENAI", "OpenAI"),
                    ("ANTHROPIC", "Anthropic Claude"),
                    ("GOOGLE_VERTEX", "Google Vertex AI"),
                    ("AWS_BEDROCK", "AWS Bedrock"),
                    ("MISTRAL", "Mistral AI"),
                    ("OLLAMA", "Ollama Local Models"),
                    ("OPENROUTER", "OpenRouter"),
                    ("OPENAI_EMBED", "OpenAI Embeddings"),
                    ("GOOGLE_EMBED", "Google Embeddings"),
                    ("SENTENCE_TRANSFORMERS", "Sentence Transformers"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("trigger", models.CharField(max_length=50)),
                (
                    "trigger_ref",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True, help_text="Snapshot of inputs.", null=True
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_input_tokens", models.IntegerField(default=0)),
                ("total_output_tokens", models.IntegerField(default=0)),
                (
                    "total_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "billed_to",
                    models.CharField(
                        choices=[("USER", "User"), ("SYSTEM", "System")],
                        default="SYSTEM",
                        max_length=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "pipeline",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="core.pipelinedefinition",
                    ),
                ),
                (
                    "triggered_by_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pipeline_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pipeline Run",
                "verbose_name_plural": "Pipeline Runs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PipelineStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("EXTRACT", "Extract"),
                            ("PREPROCESS", "Preprocess"),
                            ("AI_CALL", "AI Call"),
                            ("AGGREGATE", "Aggregate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("config", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="core.pipelinedefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pipeline Step",
                "verbose_name_plural": "Pipeline Steps",
                "ordering": ["order"],
                "unique_together": {("pipeline", "order")},
            },
        ),
        migrations.CreateModel(
            name="PipelineStepRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "input_preview",
                    models.TextField(
                        blank=True, help_text="Truncated input.", null=True
                    ),
                ),
                ("output_text", models.TextField(blank=True, null=True)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("item_type", models.CharField(blank=True, max_length=50, null=True)),
                ("item_id", models.IntegerField(blank=True, null=True)),
                (
                    "item_identifier",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_runs",
                        to="core.pipelinerun",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="step_runs",
                        to="core.pipelinestep",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pipeline Step Run",
                "verbose_name_plural": "Pipeline Step Runs",
                "ordering": ["run", "order"],
            },
        ),
        migrations.CreateModel(
            name="UserAISettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("OPENROUTER", "OpenRouter"),
                            ("AWS_BEDROCK", "AWS Bedrock"),
                        ],
                        default="OPENROUTER",
                        max_length=50,
                    ),
                ),
                ("api_key_encrypted", models.TextField(blank=True, null=True)),
                (
                    "default_model",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "monthly_budget_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="User-set soft cap. Null = unlimited.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User AI Settings",
                "verbose_name_plural": "User AI Settings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIInteractionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billed_to",
                    models.CharField(
                        choices=[("USER", "User"), ("SYSTEM", "System")],
                        default="SYSTEM",
                        max_length=10,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        help_text='What initiated this call (e.g. "notification_batch_summary").',
                        max_length=50,
                    ),
                ),
                (
                    "trigger_ref",
                    models.CharField(
                        blank=True,
                        help_text='Opaque reference, e.g. "batch:42".',
                        max_length=100,
                        null=True,
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                ("model_name", models.CharField(max_length=200)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                (
                    "cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("latency_ms", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                        default="SUCCESS",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interactions",
                        to="core.pipelinerun",
                    ),
                ),
                (
                    "pipeline_step_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interactions",
                        to="core.pipelinesteprun",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Interaction Log",
                "verbose_name_plural": "AI Interaction Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="core_aiinte_user_id_e49aea_idx",
                    ),
                    models.Index(
                        fields=["billed_to", "created_at"],
                        name="core_aiinte_billed__1f5221_idx",
                    ),
                    models.Index(
                        fields=["provider", "model_name"],
                        name="core_aiinte_provide_fb744a_idx",
                    ),
                    models.Index(
                        fields=["trigger", "created_at"],
                        name="core_aiinte_trigger_0fb99a_idx",
                    ),
                ],
            },
        ),
    ]
