# Generated by Django 5.2.16 on 2026-07-29 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_pipelinedefinition_alter_documentanalysis_provider_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecisionAIAnalysis",
            fields=[
                (
                    "decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="ai_analysis",
                        serialize=False,
                        to="core.decision",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated summary of the decision document.",
                        null=True,
                    ),
                ),
                (
                    "cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("input_tokens", models.IntegerField(blank=True, null=True)),
                ("output_tokens", models.IntegerField(blank=True, null=True)),
                ("model_used", models.CharField(blank=True, max_length=200, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decision_analyses",
                        to="core.pipelinerun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Decision AI Analysis",
                "verbose_name_plural": "Decision AI Analyses",
                "indexes": [
                    models.Index(
                        fields=["status"], name="core_decisi_status_7a3839_idx"
                    )
                ],
            },
        ),
    ]
