# Generated by Django 5.2.16 on 2026-07-30 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0081_refactor_useraisettings_fk_is_default"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useraisettings",
            options={
                "ordering": ["-is_default", "-created_at"],
                "verbose_name": "User AI Settings",
                "verbose_name_plural": "User AI Settings",
            },
        ),
    ]
