# Generated by Django 5.2.16 on 2026-07-30 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0083_user_ai_model_preference"),
    ]

    operations = [
        # 1. Drop the old primary-key constraint on decision_id so we can
        #    add a new auto-increment `id` column as the PK.
        migrations.RunSQL(
            sql="ALTER TABLE core_decisionaianalysis DROP CONSTRAINT IF EXISTS core_decisionaianalysis_pkey",
            reverse_sql="ALTER TABLE core_decisionaianalysis ADD PRIMARY KEY (decision_id)",
        ),
        # 2. Change OneToOneField(primary_key=True) → ForeignKey.
        #    Django will drop the implicit UNIQUE constraint and keep the FK.
        migrations.AlterField(
            model_name="decisionaianalysis",
            name="decision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_analyses",
                to="core.decision",
            ),
        ),
        # 3. Add the new auto-increment `id` column as the primary key.
        migrations.AddField(
            model_name="decisionaianalysis",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
