# Generated by Django 5.2.16 on 2026-08-04 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0084_decision_ai_analysis_one_to_many"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmountVerificationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("regex", "Regex / Heuristics"), ("ai", "AI / LLM")],
                        default="regex",
                        help_text="Detection method used for this run",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="Provider: 'REGEX' for regex runs, else the AI provider",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        help_text="Model: 'greek-amount-v1' for regex runs, else the LLM name",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("TEXT_EXTRACTING", "Extracting Text"),
                            ("AI_ANALYZING", "AI Analyzing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped – No Text Available"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "raw_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The decision.amount field from Diavgeia (may be inaccurate)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "calculated_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Accurate total from DecisionAmountField (FinancialCalculationService)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "ai_verified_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The amount this run decided on from the document text",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "has_discrepancy",
                    models.BooleanField(
                        default=False,
                        help_text="True if this run's chosen amount contradicts the DB amounts",
                    ),
                ),
                (
                    "discrepancy_note",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable explanation of the discrepancy",
                        null=True,
                    ),
                ),
                (
                    "ai_raw_response",
                    models.TextField(
                        blank=True,
                        help_text="Full method response / audit trail for this run",
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("input_tokens", models.IntegerField(blank=True, null=True)),
                ("output_tokens", models.IntegerField(blank=True, null=True)),
                (
                    "cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "extraction",
                    models.ForeignKey(
                        help_text="The exact document text this run was verified against",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amount_verification_runs",
                        to="core.documentextraction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Amount Verification Run",
                "verbose_name_plural": "Amount Verification Runs",
            },
        ),
        migrations.CreateModel(
            name="TextAmountCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "raw",
                    models.CharField(
                        help_text="Matched token, e.g. '10.000,00'", max_length=50
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        help_text="Char offset of the first occurrence in the text"
                    ),
                ),
                (
                    "near_keyword",
                    models.BooleanField(
                        default=False,
                        help_text="True if the occurrence is near a financial keyword",
                    ),
                ),
                (
                    "occurrence_count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many times this amount appears in the text",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_candidates",
                        to="core.amountverificationrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Text Amount Candidate",
                "verbose_name_plural": "Text Amount Candidates",
            },
        ),
        migrations.CreateModel(
            name="AmountVerificationResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chosen_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The final amount believed correct for this decision",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "has_discrepancy",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if the winning run found a discrepancy",
                    ),
                ),
                (
                    "discrepancy_note",
                    models.TextField(
                        blank=True,
                        help_text="Explanation copied from the winning run",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amount_verification",
                        to="core.decision",
                    ),
                ),
                (
                    "winning_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolutions",
                        to="core.amountverificationrun",
                    ),
                ),
                (
                    "chosen_candidate",
                    models.ForeignKey(
                        blank=True,
                        help_text="The text candidate that corresponds to the chosen amount",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.textamountcandidate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Amount Verification Resolution",
                "verbose_name_plural": "Amount Verification Resolutions",
            },
        ),
        migrations.AddIndex(
            model_name="amountverificationrun",
            index=models.Index(fields=["status"], name="core_amount_status_08e7eb_idx"),
        ),
        migrations.AddIndex(
            model_name="amountverificationrun",
            index=models.Index(
                fields=["extraction", "status"], name="core_amount_extract_76317d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="amountverificationrun",
            index=models.Index(
                fields=["-created_at"], name="core_amount_created_0d4d78_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="amountverificationrun",
            unique_together={("extraction", "method", "provider", "model", "version")},
        ),
        migrations.AddIndex(
            model_name="textamountcandidate",
            index=models.Index(
                fields=["run", "amount"], name="core_textam_run_id_d02e8d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="textamountcandidate",
            unique_together={("run", "amount")},
        ),
        migrations.AddIndex(
            model_name="amountverificationresolution",
            index=models.Index(
                fields=["-updated_at"], name="core_amount_updated_994388_idx"
            ),
        ),
    ]
