# Generated by Django 5.2.16 on 2026-08-05 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_amountverificationrun_textamountcandidate_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Drop the old amount-verification tables first (they are empty; 0085
        # created them but they were never populated). Deleting the models
        # outright drops the tables + all their indexes/constraints atomically,
        # avoiding the broken RemoveField/AlterUniqueTogether ordering Django
        # auto-generated.
        migrations.DeleteModel(name="TextAmountCandidate"),
        migrations.DeleteModel(name="AmountVerificationResolution"),
        migrations.DeleteModel(name="AmountVerificationRun"),
        migrations.CreateModel(
            name="TextProcessRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "process",
                    models.CharField(
                        db_index=True,
                        help_text="Process slug: 'amount', 'dates', 'boilerplate', ...",
                        max_length=50,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("regex", "Regex / Heuristics"), ("ai", "AI / LLM")],
                        default="regex",
                        help_text="Execution method used for this run",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="Provider: 'REGEX' for regex runs, else the AI provider",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        help_text="Model name for AI runs, else the algorithm tag",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Run-level inputs & outputs: params, raw response, computed totals, ...",
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("input_tokens", models.IntegerField(blank=True, null=True)),
                ("output_tokens", models.IntegerField(blank=True, null=True)),
                (
                    "cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "extraction",
                    models.ForeignKey(
                        help_text="The exact document text snapshot this run was executed on",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_process_runs",
                        to="core.documentextraction",
                    ),
                ),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when this process ran as part of a pipeline",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="text_process_runs",
                        to="core.pipelinerun",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="text_process_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Text Process Run",
                "verbose_name_plural": "Text Process Runs",
            },
        ),
        migrations.CreateModel(
            name="TextSpan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        db_index=True,
                        help_text="Span type: 'amount', 'date', 'boilerplate', 'signer', 'subject', 'main_point', 'useless', 'entity', ...",
                        max_length=50,
                    ),
                ),
                ("start", models.IntegerField(help_text="Char offset, inclusive")),
                ("end", models.IntegerField(help_text="Char offset, exclusive")),
                (
                    "text_snippet",
                    models.CharField(
                        help_text="The matched text (for quick preview / debugging)",
                        max_length=500,
                    ),
                ),
                (
                    "value",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Process-specific payload for this span",
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "occurrence_count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many times this span's value appears in the text",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spans",
                        to="core.textprocessrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Text Span",
                "verbose_name_plural": "Text Spans",
                "ordering": ["start"],
            },
        ),
        migrations.CreateModel(
            name="TextProcessResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("process", models.CharField(db_index=True, max_length=50)),
                (
                    "value",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The final resolved value, e.g. {'amount': '30000.00'}",
                    ),
                ),
                (
                    "has_discrepancy",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if the winning run found a discrepancy",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Explanation copied from the winning run",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_process_resolutions",
                        to="core.decision",
                    ),
                ),
                (
                    "winning_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolutions",
                        to="core.textprocessrun",
                    ),
                ),
                (
                    "chosen_span",
                    models.ForeignKey(
                        blank=True,
                        help_text="The span that corresponds to the resolved value",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.textspan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Text Process Resolution",
                "verbose_name_plural": "Text Process Resolutions",
            },
        ),
        migrations.AddIndex(
            model_name="textprocessrun",
            index=models.Index(
                fields=["process", "status"], name="core_textpr_process_a0b452_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="textprocessrun",
            index=models.Index(
                fields=["extraction", "process"], name="core_textpr_extract_d0afc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="textprocessrun",
            index=models.Index(
                fields=["-created_at"], name="core_textpr_created_ac6395_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="textprocessrun",
            unique_together={
                ("extraction", "process", "method", "provider", "model", "version")
            },
        ),
        migrations.AddIndex(
            model_name="textspan",
            index=models.Index(
                fields=["run", "label"], name="core_textsp_run_id_e429c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="textspan",
            index=models.Index(
                fields=["run", "start"], name="core_textsp_run_id_1a48bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="textprocessresolution",
            index=models.Index(
                fields=["-updated_at"], name="core_textpr_updated_c5a886_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="textprocessresolution",
            unique_together={("decision", "process")},
        ),
    ]
