# Generated by Django 5.2.16 on 2026-08-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0086_alter_amountverificationrun_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="decisionamountfield",
            name="amount_verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this field's amount was last verified/corrected.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="decisionamountfield",
            name="verified_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Corrected amount as detected from the document text. When set, this overrides 'amount' for all aggregations.",
                max_digits=15,
                null=True,
            ),
        ),
    ]
