# Generated by Django 5.2.16 on 2026-08-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0088_amount_correction_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="amountcorrectionjob",
            name="imported_since",
            field=models.DateTimeField(
                blank=True,
                help_text="Only process decisions imported (Decision.created_at) at/after this point — scopes the job to recent imports instead of the whole historical backlog.",
                null=True,
            ),
        ),
    ]
