# Generated by Django 5.2.16 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0089_amountcorrectionjob_imported_since"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="decisionamountfield",
            index=models.Index(
                condition=models.Q(("verified_amount__isnull", False)),
                fields=["decision", "verified_amount"],
                name="idx_daf_verified_amounts",
            ),
        ),
    ]
