# Generated by Django 5.2.16 on 2026-08-09 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0090_decisionamountfield_idx_daf_verified_amounts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiavgeiaFeedbackJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "reporter_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Email passed to the Diavgeia feedback API (reporterEmail). Blank uses the configured default.",
                        max_length=254,
                    ),
                ),
                (
                    "feedback_errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Diavgeia feedback error codes sent as feedBackErrors (e.g. ['FE_1']).",
                    ),
                ),
                ("limit", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "dry_run",
                    models.BooleanField(
                        default=False,
                        help_text="If True, only report what WOULD be sent (no API calls).",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("total_candidates", models.PositiveIntegerField(default=0)),
                ("processed_count", models.PositiveIntegerField(default=0)),
                ("reported", models.PositiveIntegerField(default=0)),
                ("already_reported", models.PositiveIntegerField(default=0)),
                ("skipped", models.PositiveIntegerField(default=0)),
                ("errors", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diavgeia_feedback_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiavgeiaFeedbackJobResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=30)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("response", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_job_results",
                        to="core.decision",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="core.diavgeiafeedbackjob",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["job", "status"], name="core_diavge_job_id_43647a_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DiavgeiaFeedbackReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reported",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the feedback report was accepted by the API.",
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the decision was reported to Diavgeia.",
                        null=True,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference number returned by the Diavgeia feedback API (e.g. 6a78b06a4ab4cce30ab3fd6b).",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True,
                        help_text="Raw JSON response from the Diavgeia feedback API, for debugging.",
                        null=True,
                    ),
                ),
                (
                    "reporter_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="The reporterEmail that was sent to the Diavgeia feedback API.",
                        max_length=254,
                    ),
                ),
                (
                    "feedback_errors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="The feedBackErrors codes that were sent (e.g. ['FE_1']).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.OneToOneField(
                        help_text="The decision that was reported to Diavgeia.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diavgeia_feedback_report",
                        to="core.decision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diavgeia Feedback Report",
                "verbose_name_plural": "Diavgeia Feedback Reports",
                "indexes": [
                    models.Index(
                        fields=["reported", "-reported_at"],
                        name="core_diavge_reporte_06b3fe_idx",
                    )
                ],
            },
        ),
    ]
