# Generated by Django 5.2.17 on 2026-09-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0095_search_vector_null_partial_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="decisionamountfield",
            name="invalid_amount_flagged_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this field was flagged as a non-monetary value.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="decisionamountfield",
            name="invalid_amount_reason",
            field=models.CharField(
                blank=True,
                help_text="Set when the amount is known to be a non-monetary value (e.g. 'afm_as_amount', 'kae_as_amount'). Excludes the field from all monetary aggregations.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="decisionamountfield",
            name="invalid_amount_value",
            field=models.CharField(
                blank=True,
                help_text="The non-monetary value the amount matched, for audit/display (e.g. the AFM '099370337' or the KAE digits '706273001').",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="decisionamountfield",
            index=models.Index(
                condition=models.Q(("invalid_amount_reason__isnull", False)),
                fields=["decision", "invalid_amount_reason"],
                name="idx_daf_invalid_amounts",
            ),
        ),
    ]
