# Generated by Django 5.2.17 on 2026-09-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0096_add_invalid_amount_marker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureflag",
            name="string_value",
            field=models.TextField(
                blank=True,
                help_text="For string/choice/integer-type flags: text value (integers stored as text)",
            ),
        ),
        migrations.AlterField(
            model_name="featureflag",
            name="value_type",
            field=models.CharField(
                choices=[
                    ("boolean", "Boolean (True/False)"),
                    ("list", "List (Multiple Values)"),
                    ("string", "String (Text)"),
                    ("choice", "Choice (String from Predefined List)"),
                    ("integer", "Integer (Whole Number)"),
                ],
                default="boolean",
                help_text="Type of value this flag stores",
                max_length=20,
            ),
        ),
    ]
