# Generated by Django 5.2.17 on 2026-09-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0097_alter_featureflag_string_value_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(
                fields=["created_at"], name="core_decisi_created_980735_idx"
            ),
        ),
    ]
