# Generated by Django 5.2.17 on 2026-09-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0098_decision_core_decisi_created_980735_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="amountcorrectionjob",
            name="flagged",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="amountcorrectionjob",
            name="max_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="amountcorrectionjob",
            name="mode",
            field=models.CharField(
                choices=[
                    ("decimal_shift", "Decimal separator shift (×100 / ÷100)"),
                    ("non_monetary", "Non-monetary value as amount (AFM/KAE)"),
                    ("both", "Every registered detector"),
                ],
                db_index=True,
                default="decimal_shift",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="amountcorrectionjobresult",
            name="flagged",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
